import { useState, useEffect } from "react";
import {
  BookOpen, CheckCircle2, Circle, ChevronRight, ChevronDown, Award,
  TrendingUp, BarChart3, Layers, Brain, ClipboardList, PlayCircle,
  Lightbulb, PenLine, Trophy, RotateCcw, Menu, X, Wrench, GraduationCap,
  AlertTriangle, Gamepad2, Calculator, Medal, Share2, Download, Sparkles,
  Linkedin, LayoutDashboard, Target, Flame
} from "lucide-react";

/* ===========================  BRAND  =========================== */
const NAVY = "#0D0D4B", TEAL = "#1BB8A8", NAVY_SOFT = "#1a1a6e", GOLD = "#f5b400";
const ORG = "STA Trading Academy";

/* ===========================  VISUALS  =========================== */
function LongShort(){return(<svg viewBox="0 0 420 180" className="w-full max-w-md"><defs><marker id="ah" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill={TEAL}/></marker></defs><line x1="30" y1="150" x2="390" y2="150" stroke="#cbd5e1" strokeWidth="2"/><text x="200" y="172" textAnchor="middle" fontSize="11" fill="#64748b">Time →</text><polyline points="40,120 90,90 140,100 190,60 240,80 290,40 340,55 380,30" fill="none" stroke={TEAL} strokeWidth="3"/><circle cx="40" cy="120" r="5" fill={NAVY}/><text x="44" y="112" fontSize="10" fill={NAVY}>Buy (Long)</text><line x1="340" y1="55" x2="340" y2="30" stroke="#16a34a" strokeWidth="2" markerEnd="url(#ah)"/></svg>);}
function Spread(){return(<svg viewBox="0 0 420 150" className="w-full max-w-md"><rect x="60" y="50" width="120" height="50" fill="#fee2e2" stroke="#ef4444"/><text x="120" y="42" textAnchor="middle" fontSize="11" fill="#ef4444">SELL / Bid</text><text x="120" y="82" textAnchor="middle" fontSize="16" fontWeight="bold" fill={NAVY}>1.0850</text><rect x="240" y="50" width="120" height="50" fill="#dcfce7" stroke="#16a34a"/><text x="300" y="42" textAnchor="middle" fontSize="11" fill="#16a34a">BUY / Ask</text><text x="300" y="82" textAnchor="middle" fontSize="16" fontWeight="bold" fill={NAVY}>1.0852</text><line x1="180" y1="75" x2="240" y2="75" stroke={TEAL} strokeWidth="2" strokeDasharray="4"/><text x="210" y="118" textAnchor="middle" fontSize="11" fill={TEAL} fontWeight="bold">Spread = 2 pips</text></svg>);}
function Candles(){const d=[{x:40,o:90,c:60,h:50,l:100,u:1},{x:80,o:60,c:80,h:45,l:95,u:0},{x:120,o:80,c:50,h:40,l:90,u:1},{x:160,o:50,c:40,h:30,l:70,u:1},{x:200,o:40,c:65,h:35,l:80,u:0},{x:240,o:65,c:35,h:25,l:75,u:1},{x:280,o:35,c:25,h:18,l:55,u:1}];return(<svg viewBox="0 0 340 130" className="w-full max-w-md">{d.map((k,i)=>(<g key={i}><line x1={k.x} y1={k.h} x2={k.x} y2={k.l} stroke={k.u?"#16a34a":"#ef4444"} strokeWidth="2"/><rect x={k.x-7} y={Math.min(k.o,k.c)} width="14" height={Math.abs(k.o-k.c)||2} fill={k.u?"#16a34a":"#ef4444"}/></g>))}<text x="170" y="125" textAnchor="middle" fontSize="10" fill="#64748b">Green = close up · Red = close down</text></svg>);}
function PatternViz(){const P=({x,label,wick1,bodyTop,bodyH,up})=>(<g><text x={x} y="18" textAnchor="middle" fontSize="9" fill={NAVY}>{label}</text><line x1={x} y1={wick1} x2={x} y2={wick1+44} stroke={up?"#16a34a":"#ef4444"} strokeWidth="1.5"/><rect x={x-8} y={bodyTop} width="16" height={bodyH} fill={up?"#16a34a":"#ef4444"}/></g>);return(<svg viewBox="0 0 380 90" className="w-full max-w-md"><P x="45" label="Doji" wick1="28" bodyTop="48" bodyH="3" up={1}/><P x="130" label="Hammer" wick1="28" bodyTop="32" bodyH="12" up={1}/><P x="215" label="Shooting Star" wick1="28" bodyTop="58" bodyH="12" up={0}/><P x="320" label="Engulfing" wick1="28" bodyTop="34" bodyH="34" up={1}/></svg>);}
function SR(){return(<svg viewBox="0 0 380 170" className="w-full max-w-md"><line x1="20" y1="40" x2="360" y2="40" stroke="#ef4444" strokeWidth="2" strokeDasharray="6"/><text x="24" y="34" fontSize="11" fill="#ef4444">Resistance (sellers)</text><line x1="20" y1="135" x2="360" y2="135" stroke="#16a34a" strokeWidth="2" strokeDasharray="6"/><text x="24" y="150" fontSize="11" fill="#16a34a">Support (buyers)</text><polyline points="20,120 60,45 100,90 140,42 180,100 220,44 260,110 300,48 340,80" fill="none" stroke={NAVY} strokeWidth="2.5"/></svg>);}
function RiskBar(){return(<svg viewBox="0 0 380 130" className="w-full max-w-md"><text x="190" y="18" textAnchor="middle" fontSize="12" fill={NAVY} fontWeight="bold">$10,000 Account · 1% Risk Rule</text><rect x="20" y="35" width="340" height="28" fill="#e2e8f0" rx="4"/><rect x="20" y="35" width="3.4" height="28" fill="#ef4444" rx="2"/><text x="30" y="80" fontSize="11" fill="#ef4444">Max risk per trade = $100 (red sliver)</text><text x="20" y="105" fontSize="11" fill="#64748b">Stop 50 pips away → size keeps loss ≤ $100</text></svg>);}
function Payoff({type}){const base=110,strike=200;const p={longCall:`M40 ${base} L${strike} ${base} L360 ${base-70}`,longPut:`M40 ${base-70} L${strike} ${base} L360 ${base}`,shortCall:`M40 ${base} L${strike} ${base} L360 ${base+70}`,shortPut:`M40 ${base+70} L${strike} ${base} L360 ${base}`,condor:`M40 ${base+40} L120 ${base+40} L170 ${base-30} L230 ${base-30} L280 ${base+40} L360 ${base+40}`};const l={longCall:"Long Call — bullish, limited risk",longPut:"Long Put — bearish, limited risk",shortCall:"Short Call — capped gain, big risk",shortPut:"Short Put — basis of the CSP",condor:"Iron Condor — profit if price stays in range"};return(<svg viewBox="0 0 380 170" className="w-full max-w-md"><line x1="20" y1={base} x2="370" y2={base} stroke="#cbd5e1" strokeWidth="1.5"/><line x1={strike} y1="20" x2={strike} y2="150" stroke="#94a3b8" strokeWidth="1" strokeDasharray="4"/><text x={strike} y="165" textAnchor="middle" fontSize="10" fill="#64748b">Strike</text><text x="30" y="30" fontSize="9" fill="#16a34a">Profit</text><text x="30" y="150" fontSize="9" fill="#ef4444">Loss</text><path d={p[type]} fill="none" stroke={TEAL} strokeWidth="3"/><text x="190" y="14" textAnchor="middle" fontSize="10.5" fill={NAVY} fontWeight="bold">{l[type]}</text></svg>);}
function GreeksViz(){const g=[["Δ Delta","Price move per $1; ≈ prob. ITM",TEAL],["Γ Gamma","How fast Delta changes",NAVY],["Θ Theta","Daily time decay","#ef4444"],["ν Vega","Volatility sensitivity","#f59e0b"],["ρ Rho","Interest-rate sensitivity","#8b5cf6"]];return(<div className="grid grid-cols-1 sm:grid-cols-2 gap-2 w-full max-w-lg">{g.map((x,i)=>{const c=x[2];return(<div key={i} className="rounded-lg p-3 border" style={{borderColor:c+"55",background:c+"11"}}><div className="font-bold text-sm" style={{color:c}}>{x[0]}</div><div className="text-xs text-slate-600 mt-0.5">{x[1]}</div></div>);})}</div>);}
function Wheel(){return(<svg viewBox="0 0 360 220" className="w-full max-w-md"><defs><marker id="wa" markerWidth="9" markerHeight="9" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z" fill={NAVY}/></marker></defs><circle cx="180" cy="110" r="80" fill="none" stroke={TEAL} strokeWidth="2" strokeDasharray="5"/><rect x="120" y="10" width="120" height="34" rx="6" fill={NAVY}/><text x="180" y="32" textAnchor="middle" fontSize="11" fill="#fff">1 · Sell CSP</text><rect x="250" y="92" width="100" height="34" rx="6" fill={TEAL}/><text x="300" y="114" textAnchor="middle" fontSize="10" fill="#fff">2 · Assigned</text><rect x="120" y="176" width="120" height="34" rx="6" fill={NAVY}/><text x="180" y="198" textAnchor="middle" fontSize="11" fill="#fff">3 · Sell Covered Call</text><rect x="10" y="92" width="100" height="34" rx="6" fill={TEAL}/><text x="60" y="114" textAnchor="middle" fontSize="10" fill="#fff">4 · Called away</text><path d="M242 30 Q300 50 300 90" fill="none" stroke={NAVY} strokeWidth="1.5" markerEnd="url(#wa)"/><path d="M300 128 Q280 170 242 188" fill="none" stroke={NAVY} strokeWidth="1.5" markerEnd="url(#wa)"/><path d="M118 188 Q40 170 60 128" fill="none" stroke={NAVY} strokeWidth="1.5" markerEnd="url(#wa)"/><path d="M60 90 Q60 50 118 30" fill="none" stroke={NAVY} strokeWidth="1.5" markerEnd="url(#wa)"/></svg>);}
function IntExt(){return(<svg viewBox="0 0 380 130" className="w-full max-w-md"><text x="190" y="18" textAnchor="middle" fontSize="11" fill={NAVY} fontWeight="bold">Premium $5.00 = Intrinsic + Extrinsic</text><rect x="40" y="35" width="180" height="36" fill={TEAL} rx="4"/><text x="130" y="58" textAnchor="middle" fontSize="12" fill="#fff">Intrinsic $3.00</text><rect x="220" y="35" width="120" height="36" fill={NAVY} rx="4"/><text x="280" y="58" textAnchor="middle" fontSize="11" fill="#fff">Extrinsic $2.00</text><text x="190" y="100" textAnchor="middle" fontSize="9.5" fill="#ef4444">Extrinsic decays to $0 at expiry (Theta)</text></svg>);}
const VISUALS={longshort:LongShort,spread:Spread,candles:Candles,patterns:PatternViz,sr:SR,risk:RiskBar,greeks:GreeksViz,wheel:Wheel,intext:IntExt,longCall:()=><Payoff type="longCall"/>,longPut:()=><Payoff type="longPut"/>,shortCall:()=><Payoff type="shortCall"/>,shortPut:()=><Payoff type="shortPut"/>,condor:()=><Payoff type="condor"/>};

/* ===========================  COURSES  =========================== */
const COURSES=[
{id:"c1",title:"Trading Foundations",level:"Beginner",color:TEAL,icon:TrendingUp,goal:"Understand how markets work and place your first informed paper trade.",modules:[
{id:"m1",title:"Finance Basics & Market Direction",duration:"25 min",vq:"how financial markets work for beginners forex",vt:"How Financial Markets Work",theory:"A financial market is simply a place where buyers and sellers agree on a price. Price moves because supply and demand are never perfectly balanced — more eager buyers push price up, more eager sellers push it down.\n\nYou can profit in two directions. **Going long** means buying expecting price to rise. **Going short** means selling first (borrowing the asset) expecting to buy back cheaper. In Forex and CFDs, shorting is just as easy as buying — an advantage over plain stock investing.\n\nEvery price has two numbers: the **bid** (what buyers offer) and the **ask** (what sellers want). The gap is the **spread** — effectively your cost to trade.",visual:"longshort",keyTerms:[["Long","Buy now, profit if price rises."],["Short","Sell now, profit if price falls."],["Bid / Ask","Sell price / Buy price."],["Spread","Ask minus Bid — built-in cost."]],practice:"EUR/USD shows Bid 1.0850 / Ask 1.0852. You go long. To break even, price must rise 2 pips (the spread). At 1.0872 you've gained 20 pips.",assignment:"Open a free charting site (e.g. TradingView). For EUR/USD and AAPL, write one sentence each on whether you'd go long or short today and why. Note the spread.",quiz:[{q:"You expect gold to fall. Which profits?",o:["Long","Short","Neither"],a:1,e:"Shorting profits when price falls."},{q:"The spread is:",o:["An indicator","Gap between bid & ask / your cost","Your target"],a:1,e:"Spread = Ask − Bid."}]},
{id:"m2",title:"Essential Trading Terminologies",duration:"30 min",vq:"pips lots leverage explained forex beginners",vt:"Pips, Lots & Leverage",theory:"A **pip** is the smallest standard FX move (usually the 4th decimal). A **lot** is trade size — standard 100,000 units, mini 10,000, micro 1,000.\n\n**Leverage** lets you control a large position with a small deposit. 1:100 means $1,000 controls $100,000 — it magnifies profits *and* losses equally. This is the biggest risk for beginners. **Margin** is the deposit locked to hold the position.\n\n**Order types**: a **market order** fills now; a **limit order** fills only at your price or better; a **stop order** triggers at a level (used for stop-losses).",visual:"spread",keyTerms:[["Pip","Smallest standard FX increment."],["Lot","Position size (std/mini/micro)."],["Leverage","Borrowed power — magnifies P/L."],["Margin","Deposit locked to hold a trade."],["Limit / Stop","Enter at price / trigger at level."]],practice:"1:100 leverage, $200 margin controls a $20,000 (2 mini-lot) position. A 50-pip move ≈ $100 — a 50% swing on $200. Leverage cuts both ways.",assignment:"With 1:30 leverage, how much margin opens a 1 mini-lot ($10,000) position? Then state in one line why high leverage is dangerous for a small account.",quiz:[{q:"1:100 leverage: $500 margin controls ≈",o:["$5,000","$50,000","$500"],a:1,e:"$500 × 100 = $50,000."},{q:"Which guarantees price, not fill?",o:["Market","Limit","Both"],a:1,e:"Limit fills only at your price or better."}]},
{id:"m3",title:"Key Players in the Financial Markets",duration:"20 min",vq:"key players forex market central banks institutions",vt:"Who Moves the Markets?",theory:"Markets are an ecosystem. **Central banks** (Fed, ECB) set interest rates and move whole currencies. **Banks** handle huge order flow. **Institutions** (hedge & pension funds) trade size. **Market makers** quote both bid and ask to provide liquidity.\n\nThen there's **retail traders** — individuals like you, accessing markets through a **broker**. Understanding who's on the other side helps you respect that price is driven mostly by players far larger than you — so trade *with* trends, not against giants.",visual:null,keyTerms:[["Central bank","Sets rates; biggest macro driver."],["Institution","Funds trading large size."],["Market maker","Provides liquidity quoting both sides."],["Broker","Connects retail traders to market."]],practice:"When the Fed unexpectedly raises rates, USD typically strengthens fast because institutions reprice instantly. Don't fight the move.",assignment:"Find the next Fed and ECB rate-decision dates ('central bank calendar'). Note one currency pair each could impact.",quiz:[{q:"Which most directly moves a whole currency?",o:["Retail trader","Central bank","Market maker"],a:1,e:"Central banks set rates."}]},
{id:"m4",title:"Instruments 101 — Forex, CFDs, Stocks & Options",duration:"30 min",vq:"cfd vs stocks vs options difference explained",vt:"CFDs vs Stocks vs Options",theory:"**Forex** trades one currency vs another (EUR/USD). **CFDs** let you speculate on indices, commodities, or shares *without owning* them — long or short, with leverage.\n\n**Stocks** are ownership shares; you usually buy to own and profit from appreciation and dividends. **Options** are contracts giving the *right* (not obligation) to buy or sell a stock at a set price before a date — the advanced tool we build toward.\n\nForex/CFDs suit short-term leveraged speculation; stock ownership suits longer-term investing; options sit between with defined-risk strategies.",visual:null,keyTerms:[["Forex","Currency-vs-currency trading."],["CFD","Leveraged price contract, no ownership."],["Stock","Ownership share in a company."],["Option","Right to buy/sell at a set price."]],practice:"To bet the S&P 500 falls, a CFD trader simply shorts the US500 CFD — illustrating why CFDs suit two-way speculation.",assignment:"Make a 4-row table comparing Forex, CFD, Stock, Option on: ownership? leverage? can short easily? holding time.",quiz:[{q:"Which lets you profit from a falling index easiest?",o:["Owning the stock","Shorting a CFD","Buying the fund"],a:1,e:"CFDs short with ease and leverage."},{q:"An option gives you:",o:["Obligation to buy","Right, not obligation","Company ownership"],a:1,e:"Options confer a right."}]},
{id:"m5",title:"Practical Lessons in Trading",duration:"35 min",vq:"how to place first demo trade forex stop loss take profit",vt:"Your First Demo Trade",theory:"The **anatomy of a trade**: entry, stop-loss (where you admit you're wrong), take-profit (target), and position size. Never enter without all four.\n\n**Execution realities**: your fill may differ slightly from the screen — that's **slippage**, common during news. Always trade on a **demo account** first; live prices, virtual money.\n\nProcess: (1) decide direction, (2) mark entry & stop, (3) size so the stop = a small % of account, (4) set take-profit at a sensible reward-to-risk (e.g. 2:1), (5) record it.",visual:"candles",keyTerms:[["Stop-loss","Auto-exit that caps your loss."],["Take-profit","Auto-exit at your target."],["Slippage","Expected vs actual fill gap."],["Demo account","Live prices, virtual money."]],practice:"Long EUR/USD 1.0850, stop 1.0830 (20 pips), target 1.0890 (40 pips) = 2:1. Winning even 40% of these can be profitable.",assignment:"On a demo account, place ONE trade with entry, stop, and 2:1 take-profit. Screenshot it. Write your reasoning before the result is known.",quiz:[{q:"2:1 reward-risk with a 20-pip stop targets:",o:["10 pips","40 pips","20 pips"],a:1,e:"2 × 20 = 40 pips."},{q:"Slippage is most likely during:",o:["Quiet markets","Major news","Weekends only"],a:1,e:"Fast news markets fill away from price."}]}
],capstone:{title:"Capstone 1 — Your First Trade Log",description:"Put the foundations together with a small documented exercise.",deliverables:["Execute 3 demo trades, each with entry, stop-loss & take-profit set BEFORE entry.","For each, write 2 sentences of rationale and note the spread paid.","After they close, write what you'd do differently. Record everything in the Trade Template (Tools tab)."]}},

{id:"c2",title:"Analysis, Risk & The Trading Plan",level:"Intermediate",color:GOLD,icon:BarChart3,goal:"Analyze markets two ways, control risk, and master your psychology.",modules:[
{id:"m6",title:"Basic Technical Analysis",duration:"40 min",vq:"technical analysis basics support resistance trend beginners",vt:"Technical Analysis Basics",theory:"Technical analysis reads price action to find probable next moves. The foundation is **trend**: higher highs & higher lows = uptrend; the opposite = downtrend. \"The trend is your friend.\"\n\n**Support** is a floor where buyers step in; **resistance** a ceiling where sellers appear. Trade bounces off these zones, or breakouts through them.\n\n**Candlesticks** show open/high/low/close and momentum. Key **indicators**: Moving Averages (trend), RSI (overbought/oversold), MACD (momentum). Keep it minimal — two or three beat a cluttered chart.",visual:"sr",keyTerms:[["Trend","Direction of higher/lower highs & lows."],["Support / Resistance","Price floor / ceiling."],["Moving Average","Smoothed trend line."],["RSI","Momentum: >70 overbought, <30 oversold."]],practice:"If GBP/USD bounces off 1.2500 three times, that's strong support. A long near 1.2510 with stop below 1.2480 is a clean risk-defined setup.",assignment:"On a daily chart, mark one clear support & one resistance. Add a 50-period MA and note if price is above (bullish) or below (bearish).",quiz:[{q:"Higher highs & higher lows =",o:["Downtrend","Uptrend","No trend"],a:1,e:"That structure defines an uptrend."},{q:"RSI above 70 signals:",o:["Oversold","Overbought","Neutral"],a:1,e:"RSI >70 = potentially overbought."}]},
{id:"m6c",title:"Candlestick Patterns",duration:"30 min",vq:"candlestick patterns explained trading beginners",vt:"Candlestick Patterns Explained",theory:"Each candle has a **body** (open→close) and **wicks** (the high/low extremes). Patterns of one or two candles hint at who's winning — buyers or sellers — especially at support/resistance.\n\nKey single candles: a **Doji** (tiny body) signals indecision; a **Hammer** (long lower wick at support) hints buyers rejected lower prices — bullish; a **Shooting Star** (long upper wick at resistance) is its bearish mirror.\n\nTwo-candle signals: a **Bullish Engulfing** (a big green candle swallowing the prior red) often marks a reversal up; **Bearish Engulfing** the reverse. Patterns are only meaningful *in context* — a hammer at strong support is a signal; the same candle mid-range is noise.",visual:"patterns",keyTerms:[["Body / Wick","Open→close / high-low extremes."],["Doji","Indecision; tiny body."],["Hammer","Bullish rejection at support."],["Shooting Star","Bearish rejection at resistance."],["Engulfing","Reversal: one candle swallows the prior."]],practice:"Price falls into support at 1.2500 and prints a hammer with a long lower wick. Buyers rejected the lows — a long with a stop just below the wick is a classic confirmation entry.",assignment:"On a chart, find one hammer or engulfing pattern at a support/resistance level. Screenshot it and note whether price then reversed.",quiz:[{q:"A hammer at support is:",o:["Bearish","Bullish rejection","Neutral noise"],a:1,e:"Long lower wick = buyers defended support."},{q:"A doji signals:",o:["Strong trend","Indecision","Guaranteed reversal"],a:1,e:"Tiny body = buyers and sellers balanced."}]},
{id:"m7",title:"Fundamental Analysis — Inflation & Employment",duration:"35 min",vq:"how to trade CPI NFP news forex economic calendar",vt:"Trading CPI & NFP News",theory:"Fundamentals explain *why* markets move. Two releases dominate currencies:\n\n**Inflation (CPI)** — rising inflation pressures central banks to hike rates, usually strengthening that currency. **Employment** — US **Non-Farm Payrolls (NFP)**, first Friday monthly, can swing markets violently.\n\nUse an **economic calendar** to know when high-impact data drops. Many traders flatten before NFP/CPI because volatility spikes. Fundamentals set the bias; technicals time the entry.",visual:null,keyTerms:[["CPI","Consumer Price Index — inflation."],["NFP","US Non-Farm Payrolls — jobs report."],["Economic calendar","Schedule of data by impact."],["Hawkish / Dovish","Leaning to higher / lower rates."]],practice:"Hot US CPI above expectations → traders price in Fed hikes → USD often rallies within seconds.",assignment:"Open an economic calendar. Find the next CPI and NFP dates. For one, predict in writing which way USD moves if it beats expectations, and why.",quiz:[{q:"Surprisingly high inflation makes a currency:",o:["Weaker","Stronger","Unchanged"],a:1,e:"Rate-hike expectations strengthen it."},{q:"NFP is released:",o:["Daily","First Friday monthly","Quarterly"],a:1,e:"US NFP = first Friday monthly."}]},
{id:"m8",title:"Risk Management & Position Sizing",duration:"40 min",vq:"position sizing risk management 1 percent rule trading",vt:"Position Sizing & The 1% Rule",theory:"This module keeps you alive. Golden rule: **risk only 1–2% per trade**. With $10,000 that's $100–$200 max loss. After a losing streak you're still standing.\n\n**Position sizing** turns that into a number: *Size = (Account × Risk%) ÷ (Stop distance × pip value)*. Wider stops mean smaller positions — they move together to keep dollar risk fixed.\n\nThink in **R-multiples**: 1R = your risk. A trade making twice your risk is +2R. Judging in R removes emotion. (Use the Position-Size Calculator in Tools!)",visual:"risk",keyTerms:[["1% rule","Risk ≤1–2% per trade."],["Position sizing","Size so loss = fixed $."],["R-multiple","Outcome in units of risk."],["Drawdown","Peak-to-trough account drop."]],practice:"$10,000, 1% = $100. Stop 50 pips. If 1 mini-lot = $1/pip, 50 pips risks $50/lot → trade 2 mini-lots. A 100-pip stop → only 1.",assignment:"Compute size for a $5,000 account at 1.5% risk, 40-pip stop ($1/pip per mini-lot). Show the math and final lot size. Verify with the Tools calculator.",quiz:[{q:"Best-practice risk per trade:",o:["10–20%","1–2%","50%"],a:1,e:"1–2% survives streaks."},{q:"If your stop widens, size should:",o:["Increase","Decrease","Stay same"],a:1,e:"Smaller size keeps $ risk constant."}]},
{id:"m9",title:"Trading Psychology",duration:"30 min",vq:"trading psychology discipline fear greed beginners",vt:"Master Your Trading Psychology",theory:"Most traders fail from bad psychology, not bad strategy. The two enemies: **fear** (cutting winners early, hesitating) and **greed** (oversizing, chasing, refusing losses).\n\nBiases: **loss aversion** (holding losers), **confirmation bias** (only seeing supporting info), **revenge trading** (forcing trades after a loss).\n\nAntidotes are mechanical: a written plan you follow regardless of feeling, sizing that keeps any loss bearable, and a **journal** logging the trade *and* your emotion.",visual:null,keyTerms:[["Loss aversion","Holding losers to avoid realizing loss."],["Revenge trading","Impulsive trades to recover."],["Discipline","Following your plan over emotion."],["Journaling","Logging trades + emotions."]],practice:"After two losses a trader 'doubles up' and takes a 4% hit. The fix isn't willpower — it's a hard rule: never increase size after a loss.",assignment:"Write your three 'tilt triggers' (situations where you'd break rules) and one concrete rule to defuse each.",quiz:[{q:"Holding a loser hoping it recovers is:",o:["Discipline","Loss aversion","Good risk mgmt"],a:1,e:"Classic loss aversion."}]},
{id:"m10",title:"Building a Trading Plan",duration:"35 min",vq:"how to build a trading plan strategy rules edge",vt:"How to Build a Trading Plan",theory:"A trading plan is your business document. Without it, you're gambling. It answers: **What** do I trade? **When** do I enter (exact criteria)? **How much** do I risk? **Where** do I exit? **Why** do I have an edge?\n\nYour **edge** is the specific repeatable reason your trades win over time — e.g. \"trend pullbacks to the 50-MA in London session at 2:1.\" Vague plans ('buy low, sell high') aren't edges.\n\nThe plan must be written, testable, and reviewed weekly — change one variable, track results, keep what works.",visual:null,keyTerms:[["Edge","Repeatable reason you win."],["Setup criteria","Exact conditions to enter."],["Session","Market hours you focus on."],["Review cycle","Scheduled results evaluation."]],practice:"'Long only when price is above the 50-MA AND pulls back to support AND RSI<50, risking 1%, target 2R.' Specific enough to follow and test.",assignment:"Draft your one-page trading plan: What / When / How much / Where / Why (edge).",quiz:[{q:"A trading 'edge' is:",o:["A lucky streak","Repeatable reason you profit","A type of order"],a:1,e:"A measurable, repeatable advantage."}]},
{id:"m11",title:"Small Capital & Trade Recording",duration:"25 min",vq:"how to grow small trading account safely beginners",vt:"Growing a Small Account",theory:"Starting small is smart. It forces discipline and builds real-money psychology without painful losses. Focus on **percentage returns**, not dollars — a process growing $500 by 10% grows $50,000 by 10%.\n\nFixed costs (spreads, commissions, min premiums) eat more of a tiny account, so trade fewer, higher-quality setups. Micro-lots and low-priced underlyings keep risk within your 1–2% rule.\n\n**Record every trade** — entry/exit, size, R-multiple, setup, emotion. Use the Trade Template in Tools right now.",visual:null,keyTerms:[["Compounding","Reinvesting gains to accelerate growth."],["Micro-lot","1,000-unit FX position."],["Process focus","Judge decision quality, not just P/L."],["Trade journal","Log of every trade + context."]],practice:"$500 account, 1% = $5/trade. One micro-lot with a 50-pip stop risks ≈$5 — perfectly sized. Real discipline for the price of a coffee.",assignment:"Log your last 3 demo trades in the Tools template, including emotion. Note any pattern. Then open My Dashboard to see your stats.",quiz:[{q:"On small accounts focus on:",o:["Dollar profit","% returns & process","Max leverage"],a:1,e:"% and process scale; dollars don't yet."}]}
],capstone:{title:"Capstone 2 — Trading Plan + 2-Week Journal",description:"Produce the documents a real trader runs their business on.",deliverables:["Write a complete one-page Trading Plan (What/When/How much/Where/Why).","Paper-trade 2 weeks following ONLY that plan; log every trade with R-multiples & emotion.","Write a half-page review: win rate, average R, biggest mistake, one rule to add. Check My Dashboard for the numbers."]}},

{id:"c3",title:"Options Trading & Income Strategies",level:"Advanced",color:"#8b5cf6",icon:Layers,goal:"Understand options mechanics and run a repeatable income strategy — the Wheel.",modules:[
{id:"m12",title:"Options Core Concepts & The Chain",duration:"35 min",vq:"options trading basics calls puts options chain explained",vt:"Options Basics & The Chain",theory:"An **option** is a contract for 100 shares. A **call** gives the right to *buy* at the **strike**; a **put** the right to *sell*. You pay a **premium** for that right, valid until the **expiration date**.\n\nThe **options chain** is the menu: rows are strikes, columns show calls and puts with bid/ask, volume and Greeks.\n\n**Moneyness**: a call is *in-the-money (ITM)* above the strike, *out-of-the-money (OTM)* below, *at-the-money (ATM)* equal. Puts mirror this. It drives value, risk, and strategy.",visual:null,keyTerms:[["Call / Put","Right to buy / right to sell."],["Strike","Agreed buy/sell price."],["Premium","Price paid/collected."],["Options chain","Grid of all strikes & expirations."],["Moneyness","ITM / ATM / OTM."]],practice:"Stock $105. A $100 call is $5 ITM. A $110 call is OTM. One contract = 100 shares, so a $2.00 premium costs $200.",assignment:"Open any free options chain. Find one ATM call and one ATM put on a stock you know. Record premiums and expirations.",quiz:[{q:"A call gives the right to:",o:["Sell at strike","Buy at strike","Borrow shares"],a:1,e:"Calls = right to buy."},{q:"One contract controls:",o:["1 share","10 shares","100 shares"],a:2,e:"Each contract = 100 shares."}]},
{id:"m13",title:"Long & Short Calls and Puts",duration:"35 min",vq:"long short call put payoff diagrams explained",vt:"Long vs Short Calls & Puts",theory:"Four building blocks. **Long Call**: pay premium, bullish, risk limited, big upside. **Long Put**: pay premium, bearish, profits as stock falls.\n\nThe other side: **Short Call** — collect premium, bearish/neutral, but naked short calls have unlimited risk. **Short Put** — collect premium, bullish/neutral; risk is the stock falling, but it's defined and is the engine of income strategies.\n\nSelling options makes you the 'insurance company' collecting premium and profiting from time decay.",visual:"longCall",extraVisuals:["longPut","shortCall","shortPut"],keyTerms:[["Long Call","Buy call — bullish, limited risk."],["Long Put","Buy put — bearish, limited risk."],["Short Call","Sell call — big risk if naked."],["Short Put","Sell put — basis of the CSP."]],practice:"Sell a $50 put for $1.50 → collect $150. Stays above $50? Keep it all. Below $50? You may buy 100 shares at $50 — the CSP foundation.",assignment:"Describe the payoff of all four positions, labelling max profit and max loss for each.",quiz:[{q:"Unlimited risk position:",o:["Long call","Naked short call","Long put"],a:1,e:"Uncovered short calls can lose without limit."},{q:"Selling a put profits most when stock:",o:["Crashes","Stays above strike","Goes to zero"],a:1,e:"Keep premium if it stays above strike."}]},
{id:"m14",title:"Intrinsic vs Extrinsic Value",duration:"25 min",vq:"intrinsic extrinsic value options time decay theta explained",vt:"Intrinsic vs Extrinsic Value",theory:"Premium splits in two. **Intrinsic value** is the real ITM amount: for a call, Stock − Strike (if positive). **Extrinsic value** (time value) is everything else — time remaining and volatility.\n\nA $100 call with stock at $103 priced $5.00 has $3 intrinsic, $2 extrinsic. At expiration extrinsic = $0; only intrinsic remains. This decay is **Theta** — why option *sellers* have a structural tailwind.\n\nOTM options are 100% extrinsic, which is why selling slightly-OTM options is the core of income strategies.",visual:"intext",keyTerms:[["Intrinsic","Real ITM portion."],["Extrinsic","Time + volatility portion."],["Time decay","Extrinsic erodes to expiry."],["OTM","All extrinsic, zero intrinsic."]],practice:"Stock $48, sell a $50 put for $1.20. OTM, so all $1.20 is extrinsic — pure time value you collect and watch decay.",assignment:"Pick any ITM call from a real chain. Calculate intrinsic (Stock − Strike) and subtract from premium for extrinsic. Show both.",quiz:[{q:"At expiration an option = its:",o:["Extrinsic value","Intrinsic value","Premium paid"],a:1,e:"Time value gone; only intrinsic remains."},{q:"An OTM option's premium is:",o:["All intrinsic","All extrinsic","Half each"],a:1,e:"OTM = pure extrinsic."}]},
{id:"m15",title:"The Options Greeks (Full Deep-Dive)",duration:"50 min",vq:"options greeks delta gamma theta vega rho explained simply",vt:"Options Greeks Explained",theory:"The Greeks measure how an option's price reacts to change. Master these and you trade options with intent instead of guesswork.\n\n**Delta (Δ)** — price change per $1 move in the stock, 0→1 for calls, 0→−1 for puts. It doubles as a rough *probability of finishing ITM*: a 0.30 put ≈ 30% chance ITM. It's also your 'share-equivalent' exposure — a 0.50 call behaves like 50 shares.\n\n**Gamma (Γ)** — the rate Delta changes. High near-the-money and near expiry. High gamma means direction flips fast — great for buyers, dangerous for sellers close to expiry.\n\n**Theta (Θ)** — daily time decay. Negative for buyers, positive for sellers. It accelerates in the final ~30–45 days — why income sellers target that window.\n\n**Vega (ν)** — sensitivity to *implied volatility*. Rising IV inflates all options; falling IV ('IV crush' after earnings) deflates them. Buyers want rising IV; sellers profit from falling IV.\n\n**Rho (ρ)** — sensitivity to interest rates. Smallest day-to-day; matters most for long-dated options.\n\nFor the Wheel, **Delta picks your strike (probability)** and **Theta is your daily paycheck**. Try the Strike Selector game in the Arcade.",visual:"greeks",keyTerms:[["Delta","$ move per $1; ≈ prob ITM; share-equivalent."],["Gamma","Speed Delta changes; spikes near expiry."],["Theta","Daily decay; seller's tailwind."],["Vega","IV sensitivity; 'IV crush' after earnings."],["Rho","Rate sensitivity; matters for long-dated."]],practice:"Sell a 0.30-Delta put, Theta 0.05. ≈70% chance you keep the premium, and it loses ≈$5/day to decay — a gain for you. If IV then drops, it decays even faster in your favour.",assignment:"From a real chain, find a ~0.30 Delta put. Record Delta, Theta, Vega and premium. State what the Delta implies about probability and what Theta means for a seller. Then play Strike Selector.",quiz:[{q:"The option seller's friend is:",o:["Vega","Theta","Gamma"],a:1,e:"Theta (decay) benefits sellers."},{q:"0.30 Delta put ≈ chance ITM:",o:["30%","70%","50%"],a:0,e:"Delta ≈ probability of finishing ITM."},{q:"'IV crush' after earnings hurts:",o:["Sellers","Option buyers","No one"],a:1,e:"Falling IV deflates the options buyers hold."}]},
{id:"m16",title:"Cash-Secured Puts & Covered Calls",duration:"40 min",vq:"cash secured put covered call strategy explained beginners",vt:"CSP & Covered Calls",theory:"The two safe income trades. A **Cash-Secured Put (CSP)**: sell a put and set aside cash to buy 100 shares at the strike if assigned. Collect premium upfront. Outcome A: stock stays above strike → keep premium. Outcome B: assigned → buy shares you *wanted anyway* at a discount.\n\nA **Covered Call (CC)**: own 100 shares, sell a call against them. Collect premium. Stock stays below strike → keep premium & shares. Rises above → shares 'called away' (sold) at the strike — a capped profit.\n\nTogether they get you *paid* to buy low and sell high. CSP risk: stock dropping well below strike. CC risk: missing big upside above strike.",visual:"shortPut",keyTerms:[["Cash-Secured Put","Sell put + cash to buy if assigned."],["Covered Call","Sell call vs 100 owned shares."],["Assignment","Obligation triggers — buy/sell shares."],["Called away","Shares sold at the call strike."]],practice:"You'd own XYZ at $48; it trades $50. Sell the $48 put for $1.00 → $100. Stays above $48 → ≈2% on the $4,800 reserved. Assigned → cost basis effectively $47.",assignment:"Pick a stock you'd genuinely want to own. Choose a CSP strike below price you'd accept assignment at; record premium and effective cost basis. Verify with the CSP/CC calculator in Tools.",quiz:[{q:"A CSP requires you to set aside:",o:["Nothing","Cash to buy 100 shares","100 shares"],a:1,e:"It's 'cash-secured' for assignment."},{q:"A covered call caps your:",o:["Downside","Upside above strike","Premium"],a:1,e:"Gains above the strike are forfeited."}]},
{id:"m17",title:"Expiration & Strike Selection",duration:"35 min",vq:"how to choose expiration strike delta cash secured put covered call",vt:"Choosing Expiration & Strikes",theory:"Picking **expiration (DTE)** and **strike** is the craft. The sweet spot is **30–45 DTE**: enough premium, and Theta decay accelerates fastest here. Shorter pays less; longer ties up capital.\n\n**Strike by Delta**: selling ≈**0.30 Delta** (≈70% chance of keeping premium) balances income vs assignment risk. Safer? 0.16–0.20 Delta. More premium? Closer to the money, higher assignment odds.\n\nManage actively: many traders **close at 50% of max profit** to lock gains and free capital. Avoid selling through major earnings unless intended.",visual:null,keyTerms:[["DTE","Days to expiration."],["30–45 DTE","Common selling window."],["Delta targeting","Strike by ≈assignment probability."],["50% rule","Close at half max profit."]],practice:"Sell a 35-DTE put at 0.30 Delta for $1.50. Two weeks later it's $0.75 — you've captured 50% of max profit. Close, redeploy, repeat.",assignment:"For your CSP stock, pick a 30–45 DTE expiration and ≈0.30 Delta strike. Record DTE, Delta, premium, and your 50%-profit close price.",quiz:[{q:"Common selling window:",o:["1–3 DTE","30–45 DTE","300+ DTE"],a:1,e:"Balances premium and Theta."},{q:"≈0.30 Delta put implies:",o:["30% keep premium","70% keep premium","100% assigned"],a:1,e:"≈70% expires OTM → keep premium."}]},
{id:"m18",title:"The Wheel Strategy",duration:"40 min",vq:"wheel strategy options full explanation cash secured put covered call",vt:"The Wheel Strategy",theory:"The **Wheel** combines everything into one repeatable cycle on a stock you'd happily own. Step 1: sell a **CSP**, collect premium. Step 2: not assigned? Repeat. Step 3: assigned? Now own 100 shares — sell a **Covered Call**. Step 4: called away? Sold at a profit, premium collected throughout → back to Step 1.\n\nEvery stage collects premium, lowering your cost basis. The Wheel turns 'buy low, sell high' into a *paid* mechanical routine. Main risk: a stock that falls hard and stays down — so only wheel quality names you'd hold, sized within your 1–2% rules.\n\nThis ties Course 3 to Course 2: an options income *strategy* run inside a disciplined risk-and-psychology *framework*.",visual:"wheel",keyTerms:[["The Wheel","CSP → assignment → CC → repeat."],["Cost basis reduction","Each premium lowers entry."],["Quality underlying","Stock you'd hold anyway."],["Cycle","One full loop of the Wheel."]],practice:"Wheel a stock you'd own at $48: sell $48 put ($1), assigned at $48 (basis $47). Sell $50 call ($1), called away at $50. ≈$4/share over the cycle, then repeat.",assignment:"Map one full Wheel cycle on your chosen stock: CSP (strike/premium) → assignment → CC (strike/premium) → called-away exit. Total the premium collected.",quiz:[{q:"The Wheel begins by:",o:["Buying a call","Selling a CSP","Shorting stock"],a:1,e:"Step 1 is selling a CSP."},{q:"Only wheel stocks you:",o:["Want to day-trade","Are willing to own long-term","Never researched"],a:1,e:"Assignment means owning it — pick quality."}]},
{id:"m19s",title:"Defined-Risk Spreads (Verticals & Iron Condors)",duration:"45 min",vq:"vertical spreads iron condor explained options beginners",vt:"Vertical Spreads & Iron Condors",theory:"CSPs need lots of collateral. **Spreads** cap both risk and capital, making them ideal for smaller accounts.\n\nA **vertical spread** sells one option and buys a further-OTM one of the same type/expiry. A **bull put spread** (sell a put, buy a lower put) collects net premium and profits if the stock stays up — but your max loss is just the gap between strikes minus premium, not the whole stock move. That's *defined risk*.\n\nAn **Iron Condor** stacks two credit spreads — a bull put spread below and a bear call spread above. You profit if price stays *between* them by expiration. It's the classic range-bound, high-probability income trade: small defined risk, steady Theta, no big directional bet.",visual:"condor",keyTerms:[["Vertical spread","Sell one option, buy a further-OTM hedge."],["Bull put spread","Sell put + buy lower put = defined-risk income."],["Iron Condor","Put spread + call spread; profit in a range."],["Defined risk","Max loss is capped & known upfront."]],practice:"Stock $100. Sell the $95 put, buy the $90 put → collect $1.00. Max loss = $5 width − $1 = $4 (vs ~$95 of CSP risk). Add a $105/$110 call spread and you've built an Iron Condor profiting while price stays $95–$105.",assignment:"On a chart-bound stock, sketch a bull put spread: pick two strikes, the net premium, and compute max profit (premium) and max loss (width − premium).",quiz:[{q:"A vertical spread's main benefit vs a naked option:",o:["Bigger premium","Defined, capped risk","No commissions"],a:1,e:"Buying the hedge caps the loss."},{q:"An Iron Condor profits most when price:",o:["Trends hard up","Stays in a range","Crashes"],a:1,e:"Both spreads expire worthless in the range."}]}
],capstone:{title:"Capstone 3 — Run a Full Simulated Wheel",description:"The graduation project: operate the income strategy end-to-end on paper.",deliverables:["Choose a quality stock and document a full Wheel cycle (CSP → assignment → CC → called away).","For each leg, record strike, DTE, Delta, premium, Greeks and your 50%-profit exit plan.","Total the premium collected, compute % return, and reflect tying in risk sizing & psychology from Course 2."]}}
];
COURSES.forEach(c=>c.modules.forEach((m,i)=>{m.num=i+1;}));

const GLOSSARY=[["Pip","Smallest standard FX increment."],["Lot","Std 100k, mini 10k, micro 1k units."],["Leverage","Borrowed power that magnifies P/L."],["Margin","Deposit locked to hold a position."],["Spread","Ask − Bid; built-in cost."],["Long / Short","Buy expecting rise / sell expecting fall."],["Stop-loss","Auto-exit capping a loss."],["Support / Resistance","Price floor / ceiling."],["Hammer / Doji","Bullish rejection / indecision candle."],["CPI / NFP","Inflation / US jobs data."],["R-multiple","Outcome in units of risk."],["Expectancy","Average R you expect per trade."],["Call / Put","Right to buy / sell at strike."],["Premium","Paid/collected for an option."],["Strike","Agreed buy/sell price."],["Intrinsic / Extrinsic","ITM value / time value."],["Delta","≈ probability ITM; share-equivalent."],["Theta","Daily time decay; seller's friend."],["Vega","IV sensitivity."],["CSP","Sell put + cash to buy if assigned."],["Covered Call","Sell call vs 100 owned shares."],["Vertical spread","Defined-risk sell + hedge."],["Iron Condor","Range-bound defined-risk income."],["The Wheel","CSP → assignment → CC → repeat."]];
const CHECKLIST=["In my written plan?","Direction with clear reason (technical + fundamental)?","Entry, stop & target set BEFORE entry?","Sized so loss ≤ 1–2% of account?","Reward-to-risk ≥ 2:1?","No major news (CPI/NFP/earnings) imminent?","Calm — not revenge-trading or chasing?","Logged with rationale + emotion?"];

const BADGES=[
{id:"first-steps",name:"First Steps",icon:"🚀",cond:d=>d.has("m1"),desc:"Completed your first module."},
{id:"candle-reader",name:"Candle Reader",icon:"🕯️",cond:d=>d.has("m6c"),desc:"Learned candlestick patterns."},
{id:"foundations",name:"Foundations Graduate",icon:"🟢",cond:d=>d.has("c1-cap"),desc:"Finished Course 1."},
{id:"risk-master",name:"Risk Master",icon:"🛡️",cond:d=>d.has("m8"),desc:"Mastered position sizing."},
{id:"mind-game",name:"Cool Head",icon:"🧠",cond:d=>d.has("m9"),desc:"Conquered trading psychology."},
{id:"analyst",name:"Market Analyst",icon:"🟡",cond:d=>d.has("c2-cap"),desc:"Finished Course 2."},
{id:"options-init",name:"Options Initiate",icon:"⚙️",cond:d=>d.has("m12"),desc:"Entered the options world."},
{id:"greek-scholar",name:"Greek Scholar",icon:"🏛️",cond:d=>d.has("m15"),desc:"Mastered all five Greeks."},
{id:"spread-strategist",name:"Spread Strategist",icon:"📐",cond:d=>d.has("m19s"),desc:"Learned defined-risk spreads."},
{id:"wheel-op",name:"Wheel Operator",icon:"🎡",cond:d=>d.has("m18"),desc:"Learned the full Wheel."},
{id:"options-grad",name:"Options Strategist",icon:"🔴",cond:d=>d.has("c3-cap"),desc:"Finished Course 3."},
{id:"gamer",name:"Arcade Player",icon:"🎮",cond:(d,g)=>Object.keys(g).length>0,desc:"Played a learning game."},
{id:"sharp",name:"Sharp Shooter",icon:"🎯",cond:(d,g)=>Object.values(g).some(v=>v>=5),desc:"Scored 5+ in a game."},
{id:"journalist",name:"Disciplined Journalist",icon:"📓",cond:(d,g,t)=>t>=5,desc:"Logged 5+ trades."},
{id:"graduate",name:"STA Graduate",icon:"🎓",cond:d=>["c1-cap","c2-cap","c3-cap"].every(x=>d.has(x)),desc:"Completed the entire program!"}
];

/* ===========================  HELPERS  =========================== */
const ALL_IDS=COURSES.flatMap(c=>[...c.modules.map(m=>m.id),c.id+"-cap"]);
function ytId(url){if(!url)return"";const m=url.match(/(?:v=|youtu\.be\/|embed\/|shorts\/)([\w-]{11})/);return m?m[1]:(url.length===11?url:"");}
function parseR(r){const n=parseFloat(String(r||"").replace(/[^0-9.\-]/g,""));return isNaN(n)?null:n;}
function RichText({text}){return(<div className="space-y-3">{text.split("\n\n").map((p,i)=>(<p key={i} className="text-slate-700 leading-relaxed text-[15px]">{p.split(/(\*\*[^*]+\*\*)/g).map((s,j)=>s.startsWith("**")&&s.endsWith("**")?<strong key={j} style={{color:NAVY}}>{s.slice(2,-2)}</strong>:<span key={j}>{s}</span>)}</p>))}</div>);}
function Section({icon:Icon,color,title,children,right}){return(<div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100"><div className="flex items-center gap-2 mb-3"><div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{background:color+"22"}}><Icon size={16} style={{color}}/></div><h2 className="font-bold text-[15px] flex-1" style={{color:NAVY}}>{title}</h2>{right}</div>{children}</div>);}

/* ===========================  APP  =========================== */
export default function App(){
  const [done,setDone]=useState(new Set());
  const [loaded,setLoaded]=useState(false);
  const [tab,setTab]=useState("learn");
  const [openCourse,setOpenCourse]=useState("c1");
  const [active,setActive]=useState({courseId:"c1",lessonId:"m1"});
  const [quizState,setQuizState]=useState({});
  const [sidebar,setSidebar]=useState(false);
  const [trades,setTrades]=useState([]);
  const [draft,setDraft]=useState({date:"",instrument:"",dir:"Long",entry:"",stop:"",exit:"",size:"",r:"",setup:"",emotion:""});
  const [checked,setChecked]=useState(new Set());
  const [videos,setVideos]=useState({});
  const [games,setGames]=useState({});
  const [certName,setCertName]=useState("");

  useEffect(()=>{(async()=>{
    const load=async(k)=>{try{const r=await window.storage.get(k);return r?.value?JSON.parse(r.value):null;}catch{return null;}};
    const p=await load("sta_progress");if(p)setDone(new Set(p));
    const t=await load("sta_trades");if(t)setTrades(t);
    const v=await load("sta_videos");if(v)setVideos(v);
    const g=await load("sta_games");if(g)setGames(g);
    const n=await load("sta_name");if(n)setCertName(n);
    setLoaded(true);
  })();},[]);
  const save=async(k,v)=>{try{await window.storage.set(k,JSON.stringify(v));}catch{}};
  const persistDone=s=>{setDone(new Set(s));save("sta_progress",[...s]);};
  const toggleDone=id=>{const s=new Set(done);s.has(id)?s.delete(id):s.add(id);persistDone(s);};
  const persistTrades=a=>{setTrades(a);save("sta_trades",a);};
  const persistVideos=v=>{setVideos(v);save("sta_videos",v);};
  const recordGame=(key,score)=>{const g={...games,[key]:Math.max(games[key]||0,score)};setGames(g);save("sta_games",g);};
  const persistName=n=>{setCertName(n);save("sta_name",n);};

  const overall=Math.round((done.size/ALL_IDS.length)*100);
  const courseProgress=c=>{const ids=[...c.modules.map(m=>m.id),c.id+"-cap"];return Math.round(ids.filter(i=>done.has(i)).length/ids.length*100);};
  const earnedBadges=BADGES.filter(b=>b.cond(done,games,trades.length));

  const course=COURSES.find(c=>c.id===active.courseId);
  const isCap=active.lessonId.endsWith("-cap");
  const lesson=isCap?null:course.modules.find(m=>m.id===active.lessonId);
  const goTo=(c,l)=>{setActive({courseId:c,lessonId:l});setTab("learn");setSidebar(false);window.scrollTo?.(0,0);};

  if(!loaded)return <div className="min-h-screen flex items-center justify-center text-slate-400">Loading STA Trading Academy…</div>;

  const Nav=(<div className="space-y-3">
    {[["learn",BookOpen,"Learn"],["dashboard",LayoutDashboard,"My Dashboard"],["tools",Calculator,"Tools & Calculators"],["arcade",Gamepad2,"Learning Arcade"],["achievements",Medal,"Certificates & Badges"]].map(([k,Ic,lbl])=>(
      <button key={k} onClick={()=>{setTab(k);setSidebar(false);}} className="w-full flex items-center gap-2 px-3 py-2.5 rounded-lg text-sm font-semibold transition" style={{background:tab===k?TEAL:"#f1f5f9",color:tab===k?"#fff":NAVY}}>
        <Ic size={16}/>{lbl}{k==="achievements"&&earnedBadges.length>0&&<span className="ml-auto text-[10px] px-1.5 py-0.5 rounded-full bg-white/30">{earnedBadges.length}</span>}
      </button>
    ))}
    <div className="text-[11px] font-bold text-slate-400 px-2 pt-1">COURSES</div>
    {COURSES.map(c=>{const Icon=c.icon,prog=courseProgress(c),open=openCourse===c.id;return(
      <div key={c.id} className="rounded-xl overflow-hidden border" style={{borderColor:"#e2e8f0"}}>
        <button onClick={()=>setOpenCourse(open?"":c.id)} className="w-full flex items-center gap-2 px-3 py-2.5 text-left" style={{background:"#f8fafc"}}>
          <div className="w-7 h-7 rounded-lg flex items-center justify-center shrink-0" style={{background:c.color}}><Icon size={15} color="#fff"/></div>
          <div className="flex-1 min-w-0"><div className="text-[13px] font-bold leading-tight" style={{color:NAVY}}>{c.title}</div><div className="text-[10px] text-slate-500">{c.level} · {prog}%</div></div>
          {open?<ChevronDown size={15} className="text-slate-400"/>:<ChevronRight size={15} className="text-slate-400"/>}
        </button>
        {open&&<div className="px-2 pb-2 space-y-0.5">
          {c.modules.map(m=>{const act=active.lessonId===m.id&&tab==="learn";return(
            <button key={m.id} onClick={()=>goTo(c.id,m.id)} className="w-full flex items-center gap-2 px-2 py-1.5 rounded-md text-left transition" style={{background:act?c.color+"22":"transparent"}}>
              {done.has(m.id)?<CheckCircle2 size={15} style={{color:c.color}} className="shrink-0"/>:<Circle size={15} className="text-slate-300 shrink-0"/>}
              <span className="text-[12.5px] leading-tight" style={{color:act?NAVY:"#475569",fontWeight:act?600:400}}>{m.num}. {m.title}</span>
            </button>);})}
          <button onClick={()=>goTo(c.id,c.id+"-cap")} className="w-full flex items-center gap-2 px-2 py-1.5 rounded-md text-left" style={{background:active.lessonId===c.id+"-cap"&&tab==="learn"?c.color+"22":"transparent"}}>
            {done.has(c.id+"-cap")?<CheckCircle2 size={15} style={{color:c.color}} className="shrink-0"/>:<Trophy size={15} className="text-amber-400 shrink-0"/>}
            <span className="text-[12.5px] font-semibold" style={{color:NAVY}}>Capstone Project</span>
          </button>
        </div>}
      </div>);})}
  </div>);

  return(
  <div style={{fontFamily:"'Plus Jakarta Sans', system-ui, sans-serif",background:"#f1f5f9"}} className="min-h-screen">
    <header style={{background:NAVY}} className="text-white px-4 py-3 sticky top-0 z-30 shadow-lg">
      <div className="max-w-6xl mx-auto flex items-center gap-3">
        <button className="md:hidden" onClick={()=>setSidebar(true)}><Menu size={22}/></button>
        <div className="w-9 h-9 rounded-lg flex items-center justify-center font-extrabold" style={{background:TEAL}}>STA</div>
        <div className="flex-1"><div className="font-extrabold text-[15px] leading-tight">STA Trading Academy</div><div className="text-[11px] text-slate-300">Forex · CFDs · Stocks · Options — gamified self-paced learning</div></div>
        <div className="hidden sm:flex items-center gap-3">
          <div className="text-right"><div className="text-[10px] text-slate-300">Badges</div><div className="font-bold text-sm flex items-center gap-1" style={{color:GOLD}}><Medal size={14}/>{earnedBadges.length}</div></div>
          <div className="text-right"><div className="text-[10px] text-slate-300">Progress</div><div className="font-bold text-sm" style={{color:TEAL}}>{overall}%</div></div>
        </div>
      </div>
      <div className="max-w-6xl mx-auto mt-2 h-1.5 rounded-full bg-white/15 overflow-hidden"><div className="h-full rounded-full transition-all" style={{width:overall+"%",background:TEAL}}/></div>
    </header>

    <div className="max-w-6xl mx-auto md:flex gap-5 px-4 py-5">
      <aside className="hidden md:block w-72 shrink-0"><div className="sticky top-24">{Nav}</div></aside>
      {sidebar&&<div className="fixed inset-0 z-40 md:hidden"><div className="absolute inset-0 bg-black/40" onClick={()=>setSidebar(false)}/><div className="absolute left-0 top-0 bottom-0 w-80 max-w-[85%] bg-white p-4 overflow-y-auto"><div className="flex justify-between items-center mb-4"><span className="font-bold" style={{color:NAVY}}>Menu</span><button onClick={()=>setSidebar(false)}><X size={20} className="text-slate-500"/></button></div>{Nav}</div></div>}

      <main className="flex-1 min-w-0">
        {tab==="learn"&&(isCap
          ?<CapstoneView course={course} done={done} toggleDone={toggleDone}/>
          :<LessonView course={course} lesson={lesson} done={done} toggleDone={toggleDone} quizState={quizState} setQuizState={setQuizState} videos={videos} setVideos={persistVideos}/>)}
        {tab==="dashboard"&&<Dashboard done={done} games={games} trades={trades} courseProgress={courseProgress} earned={earnedBadges} overall={overall} goTab={setTab}/>}
        {tab==="tools"&&<Tools trades={trades} draft={draft} setDraft={setDraft} persistTrades={persistTrades} checked={checked} setChecked={setChecked}/>}
        {tab==="arcade"&&<Arcade recordGame={recordGame} games={games}/>}
        {tab==="achievements"&&<Achievements done={done} games={games} earned={earnedBadges} courseProgress={courseProgress} certName={certName} setCertName={persistName} tradeCount={trades.length}/>}
      </main>
    </div>
    <footer className="text-center text-[11px] text-slate-400 py-6 px-4">Educational content only — not financial advice. Practice on demo accounts before risking real capital.</footer>
  </div>);
}

/* ===========================  LESSON  =========================== */
function VideoPlayer({lesson,videos,setVideos}){
  const [input,setInput]=useState("");
  const saved=videos[lesson.id];
  const id=saved?ytId(saved):"";
  const add=()=>{const vid=ytId(input.trim());if(vid){setVideos({...videos,[lesson.id]:vid});setInput("");}};
  const clear=()=>{const v={...videos};delete v[lesson.id];setVideos(v);};
  return(<div>
    {id?(
      <div className="rounded-xl overflow-hidden border border-slate-200 mb-3" style={{aspectRatio:"16/9"}}>
        <iframe className="w-full h-full" src={`https://www.youtube-nocookie.com/embed/${id}`} title={lesson.vt} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>
      </div>
    ):(
      <a href={`https://www.youtube.com/results?search_query=${encodeURIComponent(lesson.vq)}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-xl p-4 border border-slate-200 hover:border-slate-300 transition group mb-3">
        <div className="w-14 h-14 rounded-xl flex items-center justify-center shrink-0 group-hover:scale-105 transition" style={{background:"#8b5cf6"}}><PlayCircle size={28} color="#fff"/></div>
        <div className="flex-1 min-w-0"><div className="font-bold text-sm" style={{color:NAVY}}>{lesson.vt}</div><div className="text-[12px] text-slate-500">Tap to find lessons on YouTube → then paste the link below to embed it.</div></div>
      </a>
    )}
    <div className="flex gap-2">
      <input value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste a YouTube link to embed & save…" className="flex-1 border border-slate-200 rounded-lg px-3 py-2 text-[13px]"/>
      <button onClick={add} className="px-3 py-2 rounded-lg text-white text-[13px] font-semibold" style={{background:TEAL}}>Embed</button>
      {id&&<button onClick={clear} className="px-3 py-2 rounded-lg text-[13px] text-slate-500 border border-slate-200">Clear</button>}
    </div>
  </div>);
}

function LessonView({course,lesson,done,toggleDone,quizState,setQuizState,videos,setVideos}){
  const c=course.color,Visual=lesson.visual?VISUALS[lesson.visual]:null,isDone=done.has(lesson.id);
  const answer=(qi,oi)=>{const key=lesson.id+"-"+qi;if(quizState[key]!=null)return;setQuizState({...quizState,[key]:oi});};
  return(<div className="space-y-5">
    <div className="rounded-2xl p-5 text-white shadow-lg" style={{background:`linear-gradient(135deg, ${NAVY}, ${NAVY_SOFT})`}}>
      <div className="flex items-center gap-2 text-[11px] mb-1" style={{color:TEAL}}><span className="px-2 py-0.5 rounded-full" style={{background:c,color:"#fff"}}>{course.level}</span><span>Module {lesson.num} · {lesson.duration}</span></div>
      <h1 className="text-xl font-extrabold">{lesson.title}</h1>
    </div>
    <Section icon={BookOpen} color={c} title="Concept"><RichText text={lesson.theory}/>{Visual&&<div className="mt-4 flex justify-center bg-slate-50 rounded-xl p-4 border border-slate-100"><Visual/></div>}{lesson.extraVisuals&&<div className="mt-3 grid sm:grid-cols-3 gap-3">{lesson.extraVisuals.map(v=>{const V=VISUALS[v];return <div key={v} className="bg-slate-50 rounded-xl p-2 border border-slate-100 flex justify-center"><V/></div>;})}</div>}</Section>
    <Section icon={Layers} color={c} title="Key Terms"><div className="grid sm:grid-cols-2 gap-2">{lesson.keyTerms.map(t=>(<div key={t[0]} className="rounded-lg p-3 border border-slate-100 bg-slate-50"><div className="font-bold text-sm" style={{color:NAVY}}>{t[0]}</div><div className="text-[13px] text-slate-600 mt-0.5">{t[1]}</div></div>))}</div></Section>
    <Section icon={PlayCircle} color={c} title="Video Lesson"><VideoPlayer lesson={lesson} videos={videos} setVideos={setVideos}/></Section>
    <Section icon={Lightbulb} color={c} title="Worked Example"><div className="rounded-lg p-4 border-l-4 bg-amber-50" style={{borderColor:GOLD}}><RichText text={lesson.practice}/></div></Section>
    <Section icon={Brain} color={c} title="Knowledge Check"><div className="space-y-4">{lesson.quiz.map((q,qi)=>{const key=lesson.id+"-"+qi,sel=quizState[key];return(
      <div key={qi} className="rounded-xl p-4 border border-slate-100 bg-slate-50"><div className="font-semibold text-sm mb-2" style={{color:NAVY}}>{qi+1}. {q.q}</div><div className="space-y-1.5">{q.o.map((o,oi)=>{let bg="#fff",bd="#e2e8f0",txt="#334155";if(sel!=null){if(oi===q.a){bg="#dcfce7";bd="#16a34a";txt="#15803d";}else if(oi===sel){bg="#fee2e2";bd="#ef4444";txt="#b91c1c";}}return <button key={oi} onClick={()=>answer(qi,oi)} disabled={sel!=null} className="w-full text-left px-3 py-2 rounded-lg text-[13px] border transition" style={{background:bg,borderColor:bd,color:txt}}>{o}</button>;})}</div>{sel!=null&&<div className="mt-2 text-[12.5px] flex items-start gap-1.5" style={{color:sel===q.a?"#15803d":"#b45309"}}>{sel===q.a?<CheckCircle2 size={15} className="mt-0.5 shrink-0"/>:<AlertTriangle size={15} className="mt-0.5 shrink-0"/>}<span>{q.e}</span></div>}</div>);})}</div></Section>
    <Section icon={ClipboardList} color={c} title="Practical Assignment"><div className="rounded-lg p-4 border-l-4 bg-teal-50" style={{borderColor:TEAL}}><p className="text-[14px] text-slate-700 leading-relaxed">{lesson.assignment}</p></div></Section>
    <button onClick={()=>toggleDone(lesson.id)} className="w-full py-3.5 rounded-xl font-bold text-white flex items-center justify-center gap-2 transition shadow" style={{background:isDone?"#64748b":c}}>{isDone?<><RotateCcw size={18}/>Mark not complete</>:<><CheckCircle2 size={18}/>Mark module complete</>}</button>
  </div>);
}

function CapstoneView({course,done,toggleDone}){
  const id=course.id+"-cap",isDone=done.has(id),cap=course.capstone;
  return(<div className="space-y-5">
    <div className="rounded-2xl p-6 text-white shadow-lg text-center" style={{background:`linear-gradient(135deg, ${course.color}, ${NAVY})`}}><Trophy size={40} className="mx-auto mb-2"/><div className="text-[11px] uppercase tracking-wide opacity-80">{course.title}</div><h1 className="text-xl font-extrabold mt-1">{cap.title}</h1><p className="text-[13px] opacity-90 mt-2 max-w-md mx-auto">{cap.description}</p></div>
    <Section icon={ClipboardList} color={course.color} title="Project Deliverables"><div className="space-y-3">{cap.deliverables.map((d,i)=>(<div key={i} className="flex gap-3 items-start rounded-lg p-3 border border-slate-100 bg-slate-50"><div className="w-6 h-6 rounded-full flex items-center justify-center text-white text-xs font-bold shrink-0" style={{background:course.color}}>{i+1}</div><p className="text-[14px] text-slate-700 leading-relaxed">{d}</p></div>))}</div></Section>
    <button onClick={()=>toggleDone(id)} className="w-full py-3.5 rounded-xl font-bold text-white flex items-center justify-center gap-2 transition shadow" style={{background:isDone?"#64748b":course.color}}>{isDone?<><RotateCcw size={18}/>Mark incomplete</>:<><Trophy size={18}/>Complete capstone & earn badge</>}</button>
  </div>);
}

/* ===========================  DASHBOARD  =========================== */
function Stat({label,value,color}){return(<div className="rounded-xl bg-white border border-slate-100 p-3 text-center shadow-sm"><div className="text-2xl font-extrabold" style={{color:color||NAVY}}>{value}</div><div className="text-[11px] text-slate-500 mt-0.5">{label}</div></div>);}
function Dashboard({done,games,trades,courseProgress,earned,overall,goTab}){
  const rs=trades.map(t=>parseR(t.r)).filter(v=>v!=null);
  const wins=rs.filter(v=>v>0).length,losses=rs.filter(v=>v<0).length,decided=wins+losses;
  const winRate=decided?Math.round(wins/decided*100):0;
  const totalR=rs.reduce((s,v)=>s+v,0);
  const avgR=rs.length?totalR/rs.length:0;
  const longs=trades.filter(t=>t.dir==="Long").length,shorts=trades.filter(t=>t.dir==="Short").length;
  const opts=trades.filter(t=>t.dir==="CSP"||t.dir==="Covered Call").length;
  const modulesDone=ALL_IDS.filter(i=>done.has(i)&&!i.endsWith("-cap")).length;
  const totalModules=COURSES.reduce((s,c)=>s+c.modules.length,0);
  // cumulative R sparkline (oldest -> newest)
  const chron=[...trades].map(t=>parseR(t.r)).filter(v=>v!=null).reverse();
  let cum=0;const pts=chron.map(v=>{cum+=v;return cum;});
  const allv=[0,...pts];const mn=Math.min(...allv),mx=Math.max(...allv),rng=(mx-mn)||1;
  const W=320,H=70;const coords=pts.map((v,i)=>{const x=pts.length>1?(i/(pts.length-1))*W:W/2;const y=H-((v-mn)/rng)*H;return`${x.toFixed(1)},${y.toFixed(1)}`;});
  const zeroY=H-((0-mn)/rng)*H;
  return(<div className="space-y-5">
    <div className="rounded-2xl p-5 text-white shadow-lg" style={{background:`linear-gradient(135deg, ${NAVY}, ${TEAL})`}}><LayoutDashboard size={26} className="mb-1"/><h1 className="text-xl font-extrabold">My Dashboard</h1><p className="text-[13px] opacity-90 mt-1">Your learning progress and trading-journal analytics in one place.</p></div>

    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
      <Stat label="Overall progress" value={overall+"%"} color={TEAL}/>
      <Stat label="Modules done" value={`${modulesDone}/${totalModules}`}/>
      <Stat label="Badges earned" value={earned.length} color={GOLD}/>
      <Stat label="Trades logged" value={trades.length} color="#8b5cf6"/>
    </div>

    <Section icon={BarChart3} color={TEAL} title="Course Progress">
      <div className="space-y-3">{COURSES.map(c=>{const p=courseProgress(c);return(
        <div key={c.id}><div className="flex justify-between text-[12.5px] mb-1"><span className="font-semibold" style={{color:NAVY}}>{c.title}</span><span className="text-slate-500">{p}%</span></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full" style={{width:p+"%",background:c.color}}/></div></div>);})}</div>
    </Section>

    <Section icon={Target} color={GOLD} title="Trading Journal Analytics">
      {trades.length===0?(
        <div className="text-center py-6 text-slate-400 text-sm">No trades yet. <button onClick={()=>goTab("tools")} className="font-semibold" style={{color:TEAL}}>Log your first trade →</button></div>
      ):(<>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-4">
          <Stat label="Win rate" value={decided?winRate+"%":"—"} color={winRate>=50?"#16a34a":"#ef4444"}/>
          <Stat label="Avg result" value={(avgR>=0?"+":"")+avgR.toFixed(2)+"R"} color={avgR>=0?"#16a34a":"#ef4444"}/>
          <Stat label="Total R" value={(totalR>=0?"+":"")+totalR.toFixed(1)+"R"} color={totalR>=0?"#16a34a":"#ef4444"}/>
          <Stat label="Decided" value={`${wins}W / ${losses}L`}/>
        </div>
        {pts.length>0&&<div className="rounded-xl bg-slate-50 border border-slate-100 p-3 mb-4">
          <div className="text-[12px] font-semibold mb-1" style={{color:NAVY}}>Cumulative R (equity curve)</div>
          <svg viewBox={`0 0 ${W} ${H}`} className="w-full" style={{height:80}}>
            <line x1="0" y1={zeroY} x2={W} y2={zeroY} stroke="#cbd5e1" strokeWidth="1" strokeDasharray="3"/>
            <polyline points={coords.join(" ")} fill="none" stroke={totalR>=0?"#16a34a":"#ef4444"} strokeWidth="2.5"/>
          </svg>
        </div>}
        <div className="flex flex-wrap gap-2 text-[12px]">
          <span className="px-2.5 py-1 rounded-full bg-slate-100" style={{color:NAVY}}>Long: {longs}</span>
          <span className="px-2.5 py-1 rounded-full bg-slate-100" style={{color:NAVY}}>Short: {shorts}</span>
          <span className="px-2.5 py-1 rounded-full bg-slate-100" style={{color:NAVY}}>Options (CSP/CC): {opts}</span>
        </div>
        <p className="text-[11px] text-slate-400 mt-3">Win rate & R-stats use the "Result (R)" column of your journal — log e.g. +2, -1, +1.5.</p>
      </>)}
    </Section>

    <Section icon={Gamepad2} color="#8b5cf6" title="Arcade High Scores">
      {Object.keys(games).length===0?(
        <div className="text-center py-4 text-slate-400 text-sm"><button onClick={()=>goTab("arcade")} className="font-semibold" style={{color:"#8b5cf6"}}>Play a game →</button></div>
      ):(<div className="grid grid-cols-2 sm:grid-cols-3 gap-2">{Object.entries(games).map(([k,v])=>(<div key={k} className="rounded-lg bg-slate-50 border border-slate-100 p-2.5 text-center"><div className="font-bold" style={{color:NAVY}}>{v}</div><div className="text-[11px] text-slate-500 capitalize">{k}</div></div>))}</div>)}
    </Section>
  </div>);
}

/* ===========================  TOOLS  =========================== */
function Field({label,value,onChange,suffix}){return(<label className="block"><span className="text-[11px] font-semibold text-slate-500">{label}</span><div className="flex items-center mt-0.5"><input type="number" value={value} onChange={e=>onChange(e.target.value)} className="w-full border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>{suffix&&<span className="text-[11px] text-slate-400 ml-1 w-8">{suffix}</span>}</div></label>);}
function Result({label,value,big}){return(<div className="flex justify-between items-baseline py-1.5 border-b border-slate-100 last:border-0"><span className="text-[13px] text-slate-500">{label}</span><span className="font-bold" style={{color:NAVY,fontSize:big?18:14}}>{value}</span></div>);}

function PositionCalc(){const [acc,setAcc]=useState("10000"),[risk,setRisk]=useState("1"),[stop,setStop]=useState("50"),[pip,setPip]=useState("1");const rA=+acc*(+risk/100),lots=(+stop>0&&+pip>0)?rA/(+stop*+pip):0;return(<Section icon={Calculator} color={TEAL} title="Position-Size Calculator"><div className="grid grid-cols-2 gap-2 mb-3"><Field label="Account ($)" value={acc} onChange={setAcc}/><Field label="Risk %" value={risk} onChange={setRisk} suffix="%"/><Field label="Stop distance (pips)" value={stop} onChange={setStop}/><Field label="Pip value / mini-lot ($)" value={pip} onChange={setPip}/></div><div className="rounded-lg bg-slate-50 p-3"><Result label="Max risk this trade" value={"$"+rA.toFixed(2)}/><Result label="Position size" value={lots.toFixed(2)+" mini-lots"} big/></div><p className="text-[11px] text-slate-400 mt-2">Size = (Account × Risk%) ÷ (Stop × pip value)</p></Section>);}
function RRCalc(){const [e,setE]=useState("1.0850"),[s,setS]=useState("1.0830"),[t,setT]=useState("1.0890");const riskP=Math.abs(+e-+s),rewP=Math.abs(+t-+e),rr=riskP>0?(rewP/riskP):0;return(<Section icon={BarChart3} color={GOLD} title="Risk : Reward Calculator"><div className="grid grid-cols-3 gap-2 mb-3"><Field label="Entry" value={e} onChange={setE}/><Field label="Stop" value={s} onChange={setS}/><Field label="Target" value={t} onChange={setT}/></div><div className="rounded-lg bg-slate-50 p-3"><Result label="Risk" value={riskP.toFixed(4)}/><Result label="Reward" value={rewP.toFixed(4)}/><Result label="Reward : Risk" value={"1 : "+rr.toFixed(2)} big/></div>{rr<2&&rr>0&&<p className="text-[11px] text-amber-600 mt-2">⚠ Below the common 2:1 minimum.</p>}</Section>);}
function ExpectancyCalc(){const [wr,setWr]=useState("45"),[aw,setAw]=useState("2"),[al,setAl]=useState("1");const p=+wr/100,exp=(p*+aw)-((1-p)*+al);return(<Section icon={Flame} color="#ef4444" title="Trade Expectancy Calculator"><div className="grid grid-cols-3 gap-2 mb-3"><Field label="Win rate %" value={wr} onChange={setWr} suffix="%"/><Field label="Avg win (R)" value={aw} onChange={setAw}/><Field label="Avg loss (R)" value={al} onChange={setAl}/></div><div className="rounded-lg bg-slate-50 p-3"><Result label="Expectancy per trade" value={(exp>=0?"+":"")+exp.toFixed(2)+"R"} big/></div><p className="text-[11px] mt-2" style={{color:exp>=0?"#16a34a":"#ef4444"}}>{exp>=0?"Positive edge — this system makes money over many trades.":"Negative edge — raise win rate or reward-to-risk."}</p><p className="text-[11px] text-slate-400 mt-1">Expectancy = (Win% × AvgWin) − (Loss% × AvgLoss)</p></Section>);}
function OptionCalc(){const [type,setType]=useState("longCall"),[k,setK]=useState("100"),[prem,setPrem]=useState("2"),[n,setN]=useState("1"),[px,setPx]=useState("110");const N=+n*100,K=+k,P=+prem,S=+px;let profit;if(type==="longCall")profit=(Math.max(S-K,0)-P)*N;else if(type==="longPut")profit=(Math.max(K-S,0)-P)*N;else if(type==="shortPut")profit=(P-Math.max(K-S,0))*N;else profit=(P-Math.max(S-K,0))*N;const be=type.includes("Call")?(K+(type.startsWith("short")?-P:P)):(K-(type.startsWith("short")?-P:P));return(<Section icon={Layers} color="#8b5cf6" title="Options P/L Calculator"><div className="grid grid-cols-2 gap-2 mb-3"><label className="block col-span-2"><span className="text-[11px] font-semibold text-slate-500">Position</span><select value={type} onChange={e=>setType(e.target.value)} className="w-full border border-slate-200 rounded-lg px-2.5 py-2 text-sm mt-0.5"><option value="longCall">Long Call</option><option value="longPut">Long Put</option><option value="shortPut">Short Put (CSP)</option><option value="shortCall">Short/Covered Call</option></select></label><Field label="Strike" value={k} onChange={setK}/><Field label="Premium" value={prem} onChange={setPrem}/><Field label="Contracts" value={n} onChange={setN}/><Field label="Stock @ expiry" value={px} onChange={setPx}/></div><div className="rounded-lg bg-slate-50 p-3"><Result label="Breakeven" value={"$"+be.toFixed(2)}/><Result label="P/L at expiry" value={(profit>=0?"+":"")+"$"+profit.toFixed(2)} big/></div></Section>);}
function CSPCalc(){const [k,setK]=useState("48"),[prem,setPrem]=useState("1"),[d,setD]=useState("35");const collateral=+k*100,ret=collateral>0?(+prem*100/collateral*100):0,annual=+d>0?ret*(365/+d):0;return(<Section icon={Sparkles} color="#8b5cf6" title="CSP / Covered-Call Return"><div className="grid grid-cols-3 gap-2 mb-3"><Field label="Strike" value={k} onChange={setK}/><Field label="Premium" value={prem} onChange={setPrem}/><Field label="DTE" value={d} onChange={setD}/></div><div className="rounded-lg bg-slate-50 p-3"><Result label="Premium collected" value={"$"+(+prem*100).toFixed(0)}/><Result label="Collateral" value={"$"+collateral.toFixed(0)}/><Result label="Return over period" value={ret.toFixed(2)+"%"}/><Result label="Annualized" value={annual.toFixed(1)+"%"} big/></div></Section>);}
function CompoundCalc(){const [start,setStart]=useState("500"),[ret,setRet]=useState("5"),[m,setM]=useState("24");const final=+start*Math.pow(1+(+ret/100),+m);return(<Section icon={TrendingUp} color={TEAL} title="Compounding Projector"><div className="grid grid-cols-3 gap-2 mb-3"><Field label="Start ($)" value={start} onChange={setStart}/><Field label="Monthly %" value={ret} onChange={setRet} suffix="%"/><Field label="Months" value={m} onChange={setM}/></div><div className="rounded-lg bg-slate-50 p-3"><Result label="Total growth" value={((final/+start-1)*100).toFixed(0)+"%"}/><Result label="Projected balance" value={"$"+final.toLocaleString(undefined,{maximumFractionDigits:0})} big/></div><p className="text-[11px] text-slate-400 mt-2">Illustrative only — compounding cuts both ways.</p></Section>);}

function Tools({trades,draft,setDraft,persistTrades,checked,setChecked}){
  const f=k=>e=>setDraft({...draft,[k]:e.target.value});
  const add=()=>{if(!draft.instrument)return;persistTrades([{...draft,id:Date.now()},...trades]);setDraft({date:"",instrument:"",dir:"Long",entry:"",stop:"",exit:"",size:"",r:"",setup:"",emotion:""});};
  const del=id=>persistTrades(trades.filter(t=>t.id!==id));
  const toggle=i=>{const s=new Set(checked);s.has(i)?s.delete(i):s.add(i);setChecked(new Set(s));};
  return(<div className="space-y-5">
    <div className="rounded-2xl p-5 text-white shadow-lg" style={{background:`linear-gradient(135deg, ${TEAL}, ${NAVY})`}}><Wrench size={26} className="mb-1"/><h1 className="text-xl font-extrabold">Tools & Calculators</h1><p className="text-[13px] opacity-90 mt-1">Live calculators, your trade journal, checklist & glossary — all saved automatically.</p></div>
    <PositionCalc/><RRCalc/><ExpectancyCalc/><OptionCalc/><CSPCalc/><CompoundCalc/>
    <Section icon={PenLine} color={TEAL} title="Trade Recording Template">
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 mb-3">
        <input placeholder="Date" value={draft.date} onChange={f("date")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Instrument" value={draft.instrument} onChange={f("instrument")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <select value={draft.dir} onChange={f("dir")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"><option>Long</option><option>Short</option><option>CSP</option><option>Covered Call</option></select>
        <input placeholder="Entry" value={draft.entry} onChange={f("entry")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Stop" value={draft.stop} onChange={f("stop")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Exit" value={draft.exit} onChange={f("exit")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Size" value={draft.size} onChange={f("size")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Result (R) e.g. +2" value={draft.r} onChange={f("r")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Setup" value={draft.setup} onChange={f("setup")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm"/>
        <input placeholder="Emotion" value={draft.emotion} onChange={f("emotion")} className="border border-slate-200 rounded-lg px-2.5 py-2 text-sm col-span-2 sm:col-span-1"/>
      </div>
      <button onClick={add} className="px-4 py-2 rounded-lg text-white font-semibold text-sm" style={{background:TEAL}}>+ Add Trade</button>
      {trades.length>0&&<div className="mt-4 overflow-x-auto"><table className="w-full text-[12px]"><thead><tr className="text-left" style={{color:NAVY}}>{["Date","Instr.","Dir","Entry","Stop","Exit","Size","R","Setup","Emotion",""].map(h=><th key={h} className="px-2 py-1.5 border-b-2 border-slate-100 whitespace-nowrap font-bold">{h}</th>)}</tr></thead><tbody>{trades.map(t=>(<tr key={t.id} className="border-b border-slate-50"><td className="px-2 py-1.5 whitespace-nowrap">{t.date||"—"}</td><td className="px-2 py-1.5 font-semibold whitespace-nowrap">{t.instrument}</td><td className="px-2 py-1.5">{t.dir}</td><td className="px-2 py-1.5">{t.entry||"—"}</td><td className="px-2 py-1.5">{t.stop||"—"}</td><td className="px-2 py-1.5">{t.exit||"—"}</td><td className="px-2 py-1.5">{t.size||"—"}</td><td className="px-2 py-1.5 font-bold" style={{color:(t.r||"").includes("-")?"#ef4444":"#16a34a"}}>{t.r||"—"}</td><td className="px-2 py-1.5 max-w-[80px] truncate">{t.setup||"—"}</td><td className="px-2 py-1.5 max-w-[80px] truncate">{t.emotion||"—"}</td><td className="px-2 py-1.5"><button onClick={()=>del(t.id)} className="text-slate-300 hover:text-red-500"><X size={14}/></button></td></tr>))}</tbody></table></div>}
      <p className="text-[11px] text-slate-400 mt-2">Saved automatically. Tip: fill "Result (R)" (e.g. +2, -1) to power your Dashboard stats.</p>
    </Section>
    <Section icon={CheckCircle2} color={TEAL} title="Pre-Trade Checklist"><div className="space-y-1.5">{CHECKLIST.map((item,i)=>(<button key={i} onClick={()=>toggle(i)} className="w-full flex items-center gap-2.5 px-3 py-2 rounded-lg text-left text-[13.5px] transition" style={{background:checked.has(i)?"#dcfce7":"#f8fafc",color:checked.has(i)?"#15803d":"#334155"}}>{checked.has(i)?<CheckCircle2 size={17} className="shrink-0 text-green-600"/>:<Circle size={17} className="shrink-0 text-slate-300"/>}<span style={{textDecoration:checked.has(i)?"line-through":"none"}}>{item}</span></button>))}</div><button onClick={()=>setChecked(new Set())} className="mt-2 text-[12px] text-slate-400 hover:text-slate-600">Reset</button></Section>
    <Section icon={BookOpen} color={TEAL} title="Glossary"><div className="grid sm:grid-cols-2 gap-2">{GLOSSARY.map(([term,def])=>(<div key={term} className="rounded-lg p-2.5 border border-slate-100 bg-slate-50"><span className="font-bold text-[13px]" style={{color:NAVY}}>{term}</span><span className="text-[12.5px] text-slate-600"> — {def}</span></div>))}</div></Section>
  </div>);
}

/* ===========================  ARCADE  =========================== */
function Arcade({recordGame,games}){
  const [g,setG]=useState(null);
  const cards=[
    ["match","Term Match","Flip cards to pair each term with its meaning.","🃏",TEAL],
    ["bull","Bull or Bear?","Read the candle, call the direction. Beat the clock.","📈",GOLD],
    ["greeks","Greeks Challenge","Match each scenario to the right Greek.","🏛️","#8b5cf6"],
    ["payoff","Payoff Detective","Identify the option position from its diagram.","🔎",NAVY],
    ["strike","Strike Selector","Pick the right Delta for each income goal.","🎯","#ef4444"],
  ];
  return(<div className="space-y-5">
    <div className="rounded-2xl p-5 text-white shadow-lg" style={{background:`linear-gradient(135deg, #8b5cf6, ${NAVY})`}}><Gamepad2 size={26} className="mb-1"/><h1 className="text-xl font-extrabold">Learning Arcade</h1><p className="text-[13px] opacity-90 mt-1">Lock concepts in through play. High scores earn badges.</p></div>
    {!g&&<div className="grid sm:grid-cols-2 gap-3">{cards.map(([k,t,d,emo,col])=>(<button key={k} onClick={()=>setG(k)} className="text-left rounded-2xl p-4 bg-white border border-slate-100 shadow-sm hover:shadow-md transition"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-xl flex items-center justify-center text-2xl" style={{background:col+"22"}}>{emo}</div><div className="flex-1"><div className="font-bold" style={{color:NAVY}}>{t}</div>{games[k]!=null&&<div className="text-[11px] font-semibold" style={{color:col}}>Best: {games[k]}</div>}</div></div><p className="text-[12.5px] text-slate-500 mt-2">{d}</p></button>))}</div>}
    {g&&<div><button onClick={()=>setG(null)} className="text-[13px] text-slate-500 mb-3 flex items-center gap-1"><ChevronRight size={14} className="rotate-180"/>Back to Arcade</button>
      {g==="match"&&<MatchGame onScore={s=>recordGame("match",s)}/>}
      {g==="bull"&&<BullBear onScore={s=>recordGame("bull",s)}/>}
      {g==="greeks"&&<GreeksGame onScore={s=>recordGame("greeks",s)}/>}
      {g==="payoff"&&<PayoffGame onScore={s=>recordGame("payoff",s)}/>}
      {g==="strike"&&<StrikeGame onScore={s=>recordGame("strike",s)}/>}
    </div>}
  </div>);
}

function MatchGame({onScore}){
  const pairs=[["Pip","Smallest FX move"],["Spread","Ask − Bid"],["Theta","Time decay"],["CSP","Sell put + cash"],["Delta","≈ Prob ITM"],["Hammer","Bullish rejection"]];
  const build=()=>{const cards=[];pairs.forEach(([a,b],i)=>{cards.push({id:i+"a",pair:i,txt:a});cards.push({id:i+"b",pair:i,txt:b});});return cards.sort(()=>Math.random()-0.5);};
  const [cards,setCards]=useState(build);const [flipped,setFlipped]=useState([]);const [matched,setMatched]=useState(new Set());const [moves,setMoves]=useState(0);const [reported,setReported]=useState(false);
  const flip=c=>{if(flipped.length===2||matched.has(c.pair)||flipped.find(x=>x.id===c.id))return;const nf=[...flipped,c];setFlipped(nf);if(nf.length===2){setMoves(m=>m+1);if(nf[0].pair===nf[1].pair){const nm=new Set(matched);nm.add(nf[0].pair);setMatched(nm);setTimeout(()=>setFlipped([]),400);}else setTimeout(()=>setFlipped([]),800);}};
  const won=matched.size===pairs.length;
  useEffect(()=>{if(won&&!reported){const score=Math.max(1,pairs.length*2-Math.max(0,moves-pairs.length));onScore(score);setReported(true);}},[won]);
  const reset=()=>{setCards(build());setFlipped([]);setMatched(new Set());setMoves(0);setReported(false);};
  return(<div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm"><div className="flex justify-between items-center mb-3"><h2 className="font-bold" style={{color:NAVY}}>Term Match</h2><span className="text-[12px] text-slate-500">Moves: {moves}</span></div>{won&&<div className="rounded-lg bg-green-50 text-green-700 text-sm font-semibold p-3 mb-3 text-center">🎉 Matched all pairs in {moves} moves!</div>}<div className="grid grid-cols-3 sm:grid-cols-4 gap-2">{cards.map(c=>{const show=flipped.find(x=>x.id===c.id)||matched.has(c.pair);return(<button key={c.id} onClick={()=>flip(c)} className="aspect-[3/2] rounded-lg text-[11px] font-semibold flex items-center justify-center text-center p-1 transition" style={{background:show?(matched.has(c.pair)?"#dcfce7":TEAL+"22"):NAVY,color:show?NAVY:"#fff"}}>{show?c.txt:"STA"}</button>);})}</div><button onClick={reset} className="mt-3 text-[13px] text-slate-500">↻ Shuffle & restart</button></div>);
}

function BullBear({onScore}){
  const gen=()=>{const up=Math.random()>0.5;const o=40+Math.random()*40;const c=up?o-15-Math.random()*15:o+15+Math.random()*15;return{o,c,up};};
  const [card,setCard]=useState(gen);const [score,setScore]=useState(0);const [lives,setLives]=useState(3);const [over,setOver]=useState(false);const [fb,setFb]=useState(null);
  const guess=g=>{if(over)return;const correct=g===card.up;setFb(correct);if(correct)setScore(s=>s+1);else{const nl=lives-1;setLives(nl);if(nl<=0){setOver(true);onScore(score);return;}}setTimeout(()=>{setFb(null);setCard(gen());},500);};
  const reset=()=>{setCard(gen());setScore(0);setLives(3);setOver(false);setFb(null);};
  return(<div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm"><div className="flex justify-between items-center mb-3"><h2 className="font-bold" style={{color:NAVY}}>Bull or Bear?</h2><div className="text-[12px] text-slate-500">Score {score} · {"❤️".repeat(lives)}</div></div>{over?(<div className="text-center py-6"><div className="text-3xl mb-2">🏁</div><div className="font-bold" style={{color:NAVY}}>Final score: {score}</div><button onClick={reset} className="mt-3 px-4 py-2 rounded-lg text-white font-semibold text-sm" style={{background:GOLD}}>Play again</button></div>):(<><div className="flex justify-center my-4"><svg viewBox="0 0 80 120" className="w-20"><line x1="40" y1="10" x2="40" y2="110" stroke={card.up?"#16a34a":"#ef4444"} strokeWidth="2"/><rect x="22" y={Math.min(card.o,card.c)} width="36" height={Math.abs(card.o-card.c)} fill={card.up?"#16a34a":"#ef4444"}/></svg></div><p className="text-center text-[12px] text-slate-500 mb-3">Did this candle close UP (bullish) or DOWN (bearish)?</p><div className="grid grid-cols-2 gap-3"><button onClick={()=>guess(true)} className="py-3 rounded-xl font-bold text-white" style={{background:"#16a34a"}}>📈 Bullish</button><button onClick={()=>guess(false)} className="py-3 rounded-xl font-bold text-white" style={{background:"#ef4444"}}>📉 Bearish</button></div>{fb!=null&&<div className={"text-center mt-3 font-semibold text-sm "+(fb?"text-green-600":"text-red-500")}>{fb?"Correct!":"Not quite — the body shows the close."}</div>}</>)}</div>);
}

function GreeksGame({onScore}){
  const qs=[["The option loses value as days pass.","Theta"],["Measures ≈ probability of finishing in-the-money.","Delta"],["Prices balloon when implied volatility spikes.","Vega"],["Delta itself changes fastest near expiry.","Gamma"],["Most affected by interest-rate changes.","Rho"]];
  const opts=["Delta","Gamma","Theta","Vega","Rho"];
  const [i,setI]=useState(0),[score,setScore]=useState(0),[done,setDone]=useState(false),[sel,setSel]=useState(null);
  const pick=o=>{if(sel)return;setSel(o);if(o===qs[i][1])setScore(s=>s+1);setTimeout(()=>{if(i+1>=qs.length){setDone(true);onScore(o===qs[i][1]?score+1:score);}else{setI(i+1);setSel(null);}},700);};
  const reset=()=>{setI(0);setScore(0);setDone(false);setSel(null);};
  return(<div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm"><div className="flex justify-between items-center mb-3"><h2 className="font-bold" style={{color:NAVY}}>Greeks Challenge</h2><span className="text-[12px] text-slate-500">{Math.min(i+1,qs.length)}/{qs.length} · Score {score}</span></div>{done?(<div className="text-center py-6"><div className="text-3xl mb-2">🏛️</div><div className="font-bold" style={{color:NAVY}}>You scored {score}/{qs.length}</div><button onClick={reset} className="mt-3 px-4 py-2 rounded-lg text-white font-semibold text-sm" style={{background:"#8b5cf6"}}>Play again</button></div>):(<><div className="rounded-lg bg-slate-50 p-4 text-center text-[14px] font-semibold mb-3" style={{color:NAVY}}>{qs[i][0]}</div><div className="grid grid-cols-2 gap-2">{opts.map(o=>{let bg="#fff",bd="#e2e8f0",txt="#334155";if(sel){if(o===qs[i][1]){bg="#dcfce7";bd="#16a34a";txt="#15803d";}else if(o===sel){bg="#fee2e2";bd="#ef4444";txt="#b91c1c";}}return <button key={o} onClick={()=>pick(o)} disabled={!!sel} className="py-2.5 rounded-lg text-sm font-semibold border" style={{background:bg,borderColor:bd,color:txt}}>{o}</button>;})}</div></>)}</div>);
}

function PayoffGame({onScore}){
  const types=[["longCall","Long Call"],["longPut","Long Put"],["shortCall","Short Call"],["shortPut","Short Put"]];
  const [cur,setCur]=useState(()=>Math.floor(Math.random()*4));const [score,setScore]=useState(0);const [round,setRound]=useState(1);const [sel,setSel]=useState(null);const [done,setDone]=useState(false);
  const pick=t=>{if(sel)return;setSel(t);if(t===types[cur][0])setScore(s=>s+1);setTimeout(()=>{if(round>=5){setDone(true);onScore(t===types[cur][0]?score+1:score);}else{setRound(round+1);setCur(Math.floor(Math.random()*4));setSel(null);}},700);};
  const V=VISUALS[types[cur][0]];const reset=()=>{setScore(0);setRound(1);setSel(null);setDone(false);setCur(Math.floor(Math.random()*4));};
  return(<div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm"><div className="flex justify-between items-center mb-3"><h2 className="font-bold" style={{color:NAVY}}>Payoff Detective</h2><span className="text-[12px] text-slate-500">Round {Math.min(round,5)}/5 · Score {score}</span></div>{done?(<div className="text-center py-6"><div className="text-3xl mb-2">🔎</div><div className="font-bold" style={{color:NAVY}}>You scored {score}/5</div><button onClick={reset} className="mt-3 px-4 py-2 rounded-lg text-white font-semibold text-sm" style={{background:NAVY}}>Play again</button></div>):(<><div className="flex justify-center bg-slate-50 rounded-xl p-3 mb-3"><V/></div><p className="text-center text-[12px] text-slate-500 mb-2">Which position is this?</p><div className="grid grid-cols-2 gap-2">{types.map(([k,l])=>{let bg="#fff",bd="#e2e8f0",txt="#334155";if(sel){if(k===types[cur][0]){bg="#dcfce7";bd="#16a34a";txt="#15803d";}else if(k===sel){bg="#fee2e2";bd="#ef4444";txt="#b91c1c";}}return <button key={k} onClick={()=>pick(k)} disabled={!!sel} className="py-2.5 rounded-lg text-sm font-semibold border" style={{background:bg,borderColor:bd,color:txt}}>{l}</button>;})}</div></>)}</div>);
}

function StrikeGame({onScore}){
  const qs=[["You want the SAFEST income — highest chance of keeping premium.","0.16 Δ"],["A balanced trade: good income, ~70% chance to keep premium.","0.30 Δ"],["You're happy to be assigned and want the MOST premium.","0.50 Δ"],["Lowest assignment risk, smallest premium.","0.16 Δ"],["The textbook Wheel entry delta.","0.30 Δ"]];
  const opts=["0.16 Δ","0.30 Δ","0.50 Δ"];
  const [i,setI]=useState(0),[score,setScore]=useState(0),[done,setDone]=useState(false),[sel,setSel]=useState(null);
  const pick=o=>{if(sel)return;setSel(o);if(o===qs[i][1])setScore(s=>s+1);setTimeout(()=>{if(i+1>=qs.length){setDone(true);onScore(o===qs[i][1]?score+1:score);}else{setI(i+1);setSel(null);}},800);};
  const reset=()=>{setI(0);setScore(0);setDone(false);setSel(null);};
  return(<div className="bg-white rounded-2xl p-5 border border-slate-100 shadow-sm"><div className="flex justify-between items-center mb-3"><h2 className="font-bold" style={{color:NAVY}}>Strike Selector</h2><span className="text-[12px] text-slate-500">{Math.min(i+1,qs.length)}/{qs.length} · Score {score}</span></div>{done?(<div className="text-center py-6"><div className="text-3xl mb-2">🎯</div><div className="font-bold" style={{color:NAVY}}>You scored {score}/{qs.length}</div><div className="text-[12px] text-slate-500 mt-1">Lower Delta = safer/less premium · Higher Delta = more premium/more assignment risk.</div><button onClick={reset} className="mt-3 px-4 py-2 rounded-lg text-white font-semibold text-sm" style={{background:"#ef4444"}}>Play again</button></div>):(<><div className="rounded-lg bg-slate-50 p-4 text-center text-[14px] font-semibold mb-3" style={{color:NAVY}}>{qs[i][0]}</div><div className="grid grid-cols-3 gap-2">{opts.map(o=>{let bg="#fff",bd="#e2e8f0",txt="#334155";if(sel){if(o===qs[i][1]){bg="#dcfce7";bd="#16a34a";txt="#15803d";}else if(o===sel){bg="#fee2e2";bd="#ef4444";txt="#b91c1c";}}return <button key={o} onClick={()=>pick(o)} disabled={!!sel} className="py-2.5 rounded-lg text-sm font-semibold border" style={{background:bg,borderColor:bd,color:txt}}>{o}</button>;})}</div></>)}</div>);
}

/* ===========================  ACHIEVEMENTS  =========================== */
function downloadCert(name,courseTitle){
  const date=new Date().toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"});
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="840" viewBox="0 0 1200 840"><rect width="1200" height="840" fill="#ffffff"/><rect x="30" y="30" width="1140" height="780" fill="none" stroke="${NAVY}" stroke-width="6"/><rect x="48" y="48" width="1104" height="744" fill="none" stroke="${TEAL}" stroke-width="2"/><rect x="0" y="0" width="1200" height="120" fill="${NAVY}"/><text x="600" y="78" text-anchor="middle" fill="#fff" font-family="Arial" font-size="40" font-weight="bold">STA Trading Academy</text><text x="600" y="220" text-anchor="middle" fill="${TEAL}" font-family="Arial" font-size="26" letter-spacing="4">CERTIFICATE OF COMPLETION</text><text x="600" y="300" text-anchor="middle" fill="#475569" font-family="Arial" font-size="22">This certifies that</text><text x="600" y="380" text-anchor="middle" fill="${NAVY}" font-family="Georgia" font-size="56" font-weight="bold">${(name||"Your Name").replace(/[<>&]/g,"")}</text><line x1="350" y1="410" x2="850" y2="410" stroke="#cbd5e1" stroke-width="2"/><text x="600" y="470" text-anchor="middle" fill="#475569" font-family="Arial" font-size="22">has successfully completed</text><text x="600" y="535" text-anchor="middle" fill="${NAVY}" font-family="Arial" font-size="34" font-weight="bold">${courseTitle}</text><text x="600" y="650" text-anchor="middle" fill="#64748b" font-family="Arial" font-size="20">${date}</text><circle cx="600" cy="730" r="42" fill="${GOLD}"/><text x="600" y="738" text-anchor="middle" fill="#fff" font-family="Arial" font-size="20" font-weight="bold">STA</text></svg>`;
  const blob=new Blob([svg],{type:"image/svg+xml"});const url=URL.createObjectURL(blob);const img=new Image();
  img.onload=()=>{const cv=document.createElement("canvas");cv.width=1200;cv.height=840;const ctx=cv.getContext("2d");ctx.drawImage(img,0,0);cv.toBlob(b=>{const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="STA-Certificate-"+courseTitle.replace(/\s+/g,"-")+".png";a.click();URL.revokeObjectURL(url);});};
  img.src=url;
}
function linkedInAdd(courseTitle){window.open(`https://www.linkedin.com/profile/add?startTask=CERTIFICATION_NAME&name=${encodeURIComponent(courseTitle+" — STA Trading Academy")}&organizationName=${encodeURIComponent(ORG)}`,"_blank");}
function shareText(platform,text){const t=encodeURIComponent(text);const urls={x:`https://twitter.com/intent/tweet?text=${t}`,linkedin:`https://www.linkedin.com/feed/?shareActive=true&text=${t}`};window.open(urls[platform],"_blank");}

function Achievements({done,games,earned,courseProgress,certName,setCertName,tradeCount}){
  return(<div className="space-y-5">
    <div className="rounded-2xl p-5 text-white shadow-lg" style={{background:`linear-gradient(135deg, ${GOLD}, ${NAVY})`}}><Medal size={26} className="mb-1"/><h1 className="text-xl font-extrabold">Certificates & Badges</h1><p className="text-[13px] opacity-90 mt-1">Earn, download and share your achievements on LinkedIn & social media.</p></div>
    <Section icon={PenLine} color={NAVY} title="Your name on certificates"><input value={certName} onChange={e=>setCertName(e.target.value)} placeholder="Enter your full name" className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm"/></Section>
    <Section icon={Award} color={TEAL} title="Course Certificates">
      <div className="space-y-3">
        {COURSES.map(c=>{const prog=courseProgress(c);const ready=done.has(c.id+"-cap");return(
          <div key={c.id} className="rounded-xl border border-slate-100 p-4" style={{background:ready?"#fff":"#f8fafc"}}>
            <div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{background:ready?c.color:"#cbd5e1"}}>{ready?<Award size={20} color="#fff"/>:<Circle size={20} color="#fff"/>}</div><div className="flex-1"><div className="font-bold text-sm" style={{color:NAVY}}>{c.title}</div><div className="text-[11px] text-slate-500">{ready?"Unlocked — complete!":`Complete the capstone to unlock (${prog}%)`}</div></div></div>
            {ready&&<div className="flex flex-wrap gap-2 mt-3">
              <button onClick={()=>downloadCert(certName,c.title)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-white text-[12.5px] font-semibold" style={{background:c.color}}><Download size={14}/>Download PNG</button>
              <button onClick={()=>linkedInAdd(c.title)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-white text-[12.5px] font-semibold" style={{background:"#0a66c2"}}><Linkedin size={14}/>Add to LinkedIn</button>
              <button onClick={()=>shareText("x",`I just completed "${c.title}" at STA Trading Academy! 📈 #trading #options #forex`)} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[12.5px] font-semibold border border-slate-200" style={{color:NAVY}}><Share2 size={14}/>Share</button>
            </div>}
          </div>);})}
      </div>
    </Section>
    <Section icon={Medal} color={GOLD} title={`Badges (${earned.length}/${BADGES.length})`}>
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
        {BADGES.map(b=>{const got=earned.find(e=>e.id===b.id);return(
          <div key={b.id} className="rounded-xl p-3 text-center border" style={{borderColor:got?GOLD+"66":"#e2e8f0",background:got?GOLD+"11":"#f8fafc",opacity:got?1:0.55}}>
            <div className="text-3xl mb-1" style={{filter:got?"none":"grayscale(1)"}}>{b.icon}</div>
            <div className="font-bold text-[12px]" style={{color:NAVY}}>{b.name}</div>
            <div className="text-[10.5px] text-slate-500 mt-0.5 leading-tight">{b.desc}</div>
            {got&&<button onClick={()=>shareText("linkedin",`I earned the "${b.name}" badge at STA Trading Academy! ${b.icon} #trading #learning`)} className="mt-2 text-[10.5px] font-semibold flex items-center gap-1 mx-auto" style={{color:"#0a66c2"}}><Share2 size={11}/>Share</button>}
          </div>);})}
      </div>
    </Section>
  </div>);
}
